package app

// This file is the single source of truth for the desktop/TUI runtime
// contract. Every ActionKind and EventKind constant must appear exactly once
// in the matching All*Kinds list; an AST regression test enforces
// completeness, the desktop bridge asserts its allowlist against
// AllActionKinds, and cmd/gen-contracts renders both lists into
// frontend/src/contracts.ts so Go and TypeScript can never drift apart.

// AllActionKinds returns every action kind the runtime accepts.
func AllActionKinds() []ActionKind {
	return []ActionKind{
		ActionLogin,
		ActionLogout,
		ActionNewSession,
		ActionListSessions,
		ActionListUsage,
		ActionResumeSession,
		ActionRefreshSession,
		ActionRenameSession,
		ActionPinSession,
		ActionArchiveSession,
		ActionArchiveInactiveSessions,
		ActionMarkSessionUnread,
		ActionCompact,
		ActionResolveApproval,
		ActionResolveUserInput,
		ActionResolvePlan,
		ActionSetApprovalMode,
		ActionSetLanguage,
		ActionSetQueueMode,
		ActionReconcileAttempt,
		ActionInspectAgent,
		ActionListAgentTypes,
		ActionListPersonas,
		ActionCancelAgent,
		ActionRefreshMCP,
		ActionReconnectMCP,
		ActionSetMCPEnabled,
		ActionUpsertMCPServer,
		ActionDeleteMCPServer,
		ActionListSkills,
		ActionListPlugins,
		ActionSetPluginImported,
		ActionListHooks,
		ActionSetPluginHooksTrusted,
		ActionSetHookEnabled,
		ActionReloadSkills,
		ActionSetSkillEnabled,
		ActionListMemories,
		ActionRemember,
		ActionForgetMemory,
		ActionShowRecap,
		ActionListModels,
		ActionListModelProviders,
		ActionDiscoverProviderModels,
		ActionSetModelProvider,
		ActionSetModelEnabled,
		ActionListModelRoutes,
		ActionSetModelRoute,
		ActionResetModelRoute,
		ActionSetSubagentConcurrency,
		ActionSetSubagentDepth,
		ActionSetShellConcurrency,
		ActionSetSubagentAwait,
		ActionSetSubagentIdle,
		ActionSetChatGPTFastMode,
		ActionSetSessionPreferences,
		ActionListBackground,
		ActionStartBackground,
		ActionStopBackground,
		ActionLogsBackground,
		ActionListGitBranches,
		ActionSwitchGitBranch,
		ActionCreateGitBranch,
	}
}

// AllEventKinds returns every runtime event kind the app can emit.
func AllEventKinds() []EventKind {
	return []EventKind{
		EventBootstrapDone,
		EventSessionLoaded,
		EventTodoUpdated,
		EventRunStarted,
		EventContextUsage,
		EventContextProfile,
		EventAgentState,
		EventAgentDetail,
		EventProviderRetry,
		EventThinkingDelta,
		EventTextDelta,
		EventProjectionResync,
		EventToolStarted,
		EventToolUpdate,
		EventToolFinished,
		EventDiffReady,
		EventApprovalRequested,
		EventApprovalResolved,
		EventUserInputRequested,
		EventUserInputResolved,
		EventPlanProposed,
		EventPlanResolved,
		EventApprovalMode,
		EventModelCatalog,
		EventModelProviders,
		EventSkillCatalog,
		EventPluginCatalog,
		EventHookCatalog,
		EventAuthState,
		EventMCPState,
		EventRecoveryState,
		EventRunFinished,
		EventRunFailed,
		EventRunCancelled,
		EventHookStarted,
		EventHookFinished,
		EventHookDiagnostic,
		EventMemoryState,
		EventRecapState,
		EventModelRoutes,
		EventBackgroundState,
		EventBackgroundLogs,
		EventGitBranches,
		EventUsageReport,
	}
}
