// Command gen-contracts renders the Go runtime contract (action and event
// kinds) into frontend/src/contracts.ts so the TypeScript side can never
// drift from the Go source of truth. Run via `make contracts`; CI verifies
// freshness via `make contracts-check`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"

	azemapp "github.com/Viking602/azem/internal/app"
	"github.com/Viking602/azem/internal/desktop"
)

const header = `// Code generated by cmd/gen-contracts; DO NOT EDIT.
// The Go source of truth is internal/app/contracts.go (plus the desktop
// bridge-local event kinds). Regenerate with: make contracts
`

func main() {
	check := flag.Bool("check", false, "verify the generated file is up to date instead of writing it")
	output := flag.String("output", filepath.Join("frontend", "src", "contracts.ts"), "output path for the generated TypeScript contract")
	flag.Parse()

	generated := render()

	if *check {
		current, err := os.ReadFile(*output)
		if err != nil {
			fatalf("read %s: %v (run `make contracts`)", *output, err)
		}
		if !bytes.Equal(current, generated) {
			fatalf("%s is stale; run `make contracts` to regenerate it", *output)
		}
		return
	}

	if err := os.WriteFile(*output, generated, 0o644); err != nil {
		fatalf("write %s: %v", *output, err)
	}
}

func render() []byte {
	var buf bytes.Buffer
	buf.WriteString(header)

	buf.WriteString("\n/** Every action kind accepted by the runtime (internal/app AllActionKinds). */\n")
	buf.WriteString("export type ActionKind =\n")
	for _, kind := range azemapp.AllActionKinds() {
		fmt.Fprintf(&buf, "  | %q\n", string(kind))
	}
	buf.WriteString(";\n")

	buf.WriteString("\n/** Every runtime event kind (internal/app AllEventKinds) plus desktop bridge-local kinds. */\n")
	buf.WriteString("export type EventKind =\n")
	for _, kind := range azemapp.AllEventKinds() {
		fmt.Fprintf(&buf, "  | %q\n", string(kind))
	}
	for _, kind := range desktop.LocalEventKinds() {
		fmt.Fprintf(&buf, "  | %q\n", kind)
	}
	buf.WriteString(";\n")

	buf.WriteString("\nexport const ACTION_KINDS: readonly ActionKind[] = [\n")
	for _, kind := range azemapp.AllActionKinds() {
		fmt.Fprintf(&buf, "  %q,\n", string(kind))
	}
	buf.WriteString("];\n")

	buf.WriteString("\nexport const EVENT_KINDS: readonly EventKind[] = [\n")
	for _, kind := range azemapp.AllEventKinds() {
		fmt.Fprintf(&buf, "  %q,\n", string(kind))
	}
	for _, kind := range desktop.LocalEventKinds() {
		fmt.Fprintf(&buf, "  %q,\n", kind)
	}
	buf.WriteString("];\n")

	return buf.Bytes()
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-contracts: "+format+"\n", args...)
	os.Exit(1)
}
