// Command gen-contracts renders the Go runtime contract into the native Rust
// desktop client. Run via `make contracts`; CI verifies freshness with
// `make contracts-check`.
package main

import (
	"bytes"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"unicode"

	azemapp "github.com/Viking602/azem/internal/app"
	"github.com/Viking602/azem/internal/desktop"
	"github.com/Viking602/azem/internal/desktopipc"
)

const rustHeader = `// Code generated by cmd/gen-contracts; DO NOT EDIT.
// The Go source of truth is internal/desktopipc/protocol.go and
// internal/app/contracts.go. Regenerate with: make contracts.
`

func main() {
	check := flag.Bool("check", false, "verify generated files are current")
	rustOutput := flag.String("rust-output", filepath.Join("gpui", "crates", "azem-ipc", "src", "generated.rs"), "Rust output path")
	flag.Parse()

	outputs := []struct {
		path string
		data []byte
	}{{*rustOutput, renderRust()}}
	for _, output := range outputs {
		if *check {
			current, err := os.ReadFile(output.path)
			if err != nil {
				fatalf("read %s: %v (run `make contracts`)", output.path, err)
			}
			if !bytes.Equal(current, output.data) {
				fatalf("%s is stale; run `make contracts`", output.path)
			}
			continue
		}
		if err := os.MkdirAll(filepath.Dir(output.path), 0o755); err != nil {
			fatalf("create output directory for %s: %v", output.path, err)
		}
		if err := os.WriteFile(output.path, output.data, 0o644); err != nil {
			fatalf("write %s: %v", output.path, err)
		}
	}
}

func renderRust() []byte {
	var buf bytes.Buffer
	buf.WriteString(rustHeader)
	buf.WriteString("\nuse serde::{Deserialize, Serialize};\nuse serde_json::Value;\n\n")
	fmt.Fprintf(&buf, "pub const PROTOCOL_VERSION: u32 = %d;\n", desktopipc.ProtocolVersion)
	fmt.Fprintf(&buf, "pub const MAX_CONTROL_FRAME_BYTES: usize = %d;\n", desktopipc.MaxControlFrameBytes)
	fmt.Fprintf(&buf, "pub const MAX_BINARY_CHUNK_BYTES: usize = %d;\n", desktopipc.MaxBinaryChunkBytes)
	fmt.Fprintf(&buf, "pub const MAX_REASSEMBLED_BINARY: usize = %d;\n\n", desktopipc.MaxReassembledBinary)

	renderRustEnum(&buf, "Method", methodStrings())
	renderRustEnum(&buf, "ActionKind", actionStrings())
	renderRustEnum(&buf, "EventKind", eventStrings())
	buf.WriteString(`#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolError {
    pub code: String,
    pub message: String,
    #[serde(default)]
    pub retryable: bool,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BinaryMetadata {
    pub transfer_id: String,
    #[serde(default)]
    pub purpose: String,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub sequence: u64,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub media_type: String,
    pub byte_length: i64,
    pub sha256: String,
    #[serde(default)]
    pub index: usize,
    #[serde(default)]
    pub count: usize,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Envelope {
    pub version: u32,
    pub kind: String,
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub client_id: String,
    #[serde(default)]
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<Method>,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub sequence: u64,
    #[serde(default)]
    pub payload: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ProtocolError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub binary: Option<BinaryMetadata>,
}

impl Envelope {
    pub fn request(id: impl Into<String>, method: Method, payload: Value) -> Self {
        Self {
            version: PROTOCOL_VERSION,
            kind: "request".into(),
            id: id.into(),
            client_id: String::new(),
            workspace_id: String::new(),
            method: Some(method),
            channel: String::new(),
            sequence: 0,
            payload,
            error: None,
            binary: None,
        }
    }
}
`)
	return buf.Bytes()
}

func renderRustEnum(buf *bytes.Buffer, name string, values []string) {
	fmt.Fprintf(buf, "#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, Hash, PartialEq)]\n")
	fmt.Fprintf(buf, "pub enum %s {\n", name)
	for _, value := range values {
		fmt.Fprintf(buf, "    #[serde(rename = %q)]\n    %s,\n", value, rustIdentifier(value))
	}
	buf.WriteString("}\n\n")
}

func methodStrings() []string {
	methods := desktopipc.AllMethods()
	values := make([]string, len(methods))
	for index, method := range methods {
		values[index] = string(method)
	}
	return values
}

func actionStrings() []string {
	kinds := azemapp.AllActionKinds()
	values := make([]string, len(kinds))
	for index, kind := range kinds {
		values[index] = string(kind)
	}
	return values
}

func eventStrings() []string {
	kinds := azemapp.AllEventKinds()
	values := make([]string, 0, len(kinds)+len(desktop.LocalEventKinds()))
	for _, kind := range kinds {
		values = append(values, string(kind))
	}
	return append(values, desktop.LocalEventKinds()...)
}

func rustIdentifier(value string) string {
	var result strings.Builder
	upper := true
	for _, current := range value {
		if !unicode.IsLetter(current) && !unicode.IsDigit(current) {
			upper = true
			continue
		}
		if upper {
			result.WriteRune(unicode.ToUpper(current))
			upper = false
		} else {
			result.WriteRune(current)
		}
	}
	identifier := result.String()
	if identifier == "" || unicode.IsDigit(rune(identifier[0])) {
		return "Value" + identifier
	}
	return identifier
}

func fatalf(format string, args ...any) {
	fmt.Fprintf(os.Stderr, "gen-contracts: "+format+"\n", args...)
	os.Exit(1)
}
