// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgen

type Account struct {
	ID            string `db:"id"`
	ProviderID    string `db:"provider_id"`
	Email         string `db:"email"`
	DisplayName   string `db:"display_name"`
	Plan          string `db:"plan"`
	CredentialRef string `db:"credential_ref"`
	Status        string `db:"status"`
	CreatedAt     int64  `db:"created_at"`
	UpdatedAt     int64  `db:"updated_at"`
}

type AuthCredential struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
	Data       string `db:"data"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

type ContextArtifact struct {
	ID        string `db:"id"`
	SessionID string `db:"session_id"`
	RunID     string `db:"run_id"`
	Kind      string `db:"kind"`
	Sha256    string `db:"sha256"`
	Payload   []byte `db:"payload"`
	Preview   string `db:"preview"`
	CreatedAt int64  `db:"created_at"`
}

type Event struct {
	RunID      string `db:"run_id"`
	Sequence   int64  `db:"sequence"`
	RecordedAt int64  `db:"recorded_at"`
	Data       []byte `db:"data"`
}

type HistoryFt struct {
	SessionID  string `db:"session_id"`
	SourceType string `db:"source_type"`
	SourceID   string `db:"source_id"`
	Content    string `db:"content"`
}

type Lease struct {
	ID        string `db:"id"`
	RunID     string `db:"run_id"`
	TaskID    string `db:"task_id"`
	HolderID  string `db:"holder_id"`
	Status    string `db:"status"`
	ExpiresAt int64  `db:"expires_at"`
	Version   int64  `db:"version"`
	Data      []byte `db:"data"`
}

type MemoriesFt struct {
	Content string `db:"content"`
}

type Memory struct {
	MemoryRowid int64  `db:"memory_rowid"`
	ID          string `db:"id"`
	Content     string `db:"content"`
	Anchor      string `db:"anchor"`
	SessionID   string `db:"session_id"`
	Provenance  string `db:"provenance"`
	Status      string `db:"status"`
	Importance  int64  `db:"importance"`
	CreatedAt   int64  `db:"created_at"`
	UpdatedAt   int64  `db:"updated_at"`
}

type ModelCatalog struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
	ModelID    string `db:"model_id"`
	Etag       string `db:"etag"`
	FetchedAt  int64  `db:"fetched_at"`
	ExpiresAt  int64  `db:"expires_at"`
	Data       []byte `db:"data"`
}

type ProviderRequest struct {
	RequestID            string `db:"request_id"`
	ProviderRequestID    string `db:"provider_request_id"`
	SessionID            string `db:"session_id"`
	RunID                string `db:"run_id"`
	RequestKind          string `db:"request_kind"`
	Provider             string `db:"provider"`
	Model                string `db:"model"`
	Transport            string `db:"transport"`
	CacheEpoch           int64  `db:"cache_epoch"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	InputTokens          int64  `db:"input_tokens"`
	CachedTokens         int64  `db:"cached_tokens"`
	CacheWriteTokens     int64  `db:"cache_write_tokens"`
	OutputTokens         int64  `db:"output_tokens"`
	ReasoningTokens      int64  `db:"reasoning_tokens"`
	TotalTokens          int64  `db:"total_tokens"`
	CacheReported        int64  `db:"cache_reported"`
	Status               string `db:"status"`
	StartedAt            int64  `db:"started_at"`
	CompletedAt          int64  `db:"completed_at"`
}

type Recap struct {
	SessionID       string `db:"session_id"`
	Anchor          string `db:"anchor"`
	CoveredBoundary string `db:"covered_boundary"`
	Revision        int64  `db:"revision"`
	Goal            string `db:"goal"`
	Summary         string `db:"summary"`
	OpenItems       string `db:"open_items"`
	UpdatedAt       int64  `db:"updated_at"`
}

type Record struct {
	Kind           string `db:"kind"`
	Key1           string `db:"key1"`
	Key2           string `db:"key2"`
	RunID          string `db:"run_id"`
	TaskID         string `db:"task_id"`
	Status         string `db:"status"`
	CreatedAt      int64  `db:"created_at"`
	ToolName       string `db:"tool_name"`
	IdempotencyKey string `db:"idempotency_key"`
	Data           []byte `db:"data"`
}

type Session struct {
	ID         string `db:"id"`
	Title      string `db:"title"`
	ProviderID string `db:"provider_id"`
	ModelID    string `db:"model_id"`
	Reasoning  string `db:"reasoning"`
	AgentMode  string `db:"agent_mode"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

type SessionBlock struct {
	SessionID string `db:"session_id"`
	Sequence  int64  `db:"sequence"`
	Kind      string `db:"kind"`
	RunID     string `db:"run_id"`
	AgentID   string `db:"agent_id"`
	Data      []byte `db:"data"`
}

type SessionProjection struct {
	SessionID            string `db:"session_id"`
	LastRunID            string `db:"last_run_id"`
	Blocks               []byte `db:"blocks"`
	UpdatedAt            int64  `db:"updated_at"`
	ModelHistory         []byte `db:"model_history"`
	Usage                []byte `db:"usage"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	CacheEpoch           int64  `db:"cache_epoch"`
	CacheIdentityHash    string `db:"cache_identity_hash"`
}

type SessionTodo struct {
	SessionID string `db:"session_id"`
	Goal      string `db:"goal"`
	Revision  int64  `db:"revision"`
	Phases    []byte `db:"phases"`
	UpdatedAt int64  `db:"updated_at"`
}

type SubagentRun struct {
	ID                  string `db:"id"`
	SessionID           string `db:"session_id"`
	ParentRunID         string `db:"parent_run_id"`
	ParentAgentID       string `db:"parent_agent_id"`
	ToolCallID          string `db:"tool_call_id"`
	ChildRunID          string `db:"child_run_id"`
	Description         string `db:"description"`
	SubagentType        string `db:"subagent_type"`
	State               string `db:"state"`
	Summary             string `db:"summary"`
	Provider            string `db:"provider"`
	Model               string `db:"model"`
	Reasoning           string `db:"reasoning"`
	CapabilityMode      string `db:"capability_mode"`
	RequestedIsolation  string `db:"requested_isolation"`
	Isolation           string `db:"isolation"`
	Cwd                 string `db:"cwd"`
	Background          int64  `db:"background"`
	Output              string `db:"output"`
	Error               string `db:"error"`
	Warning             string `db:"warning"`
	Transcript          []byte `db:"transcript"`
	ToolCalls           int64  `db:"tool_calls"`
	Turns               int64  `db:"turns"`
	TokensUsed          int64  `db:"tokens_used"`
	ToolsUsed           []byte `db:"tools_used"`
	WorktreePath        string `db:"worktree_path"`
	CompletionDelivered int64  `db:"completion_delivered"`
	StartedAt           int64  `db:"started_at"`
	FinishedAt          int64  `db:"finished_at"`
}

type ToolCallCharge struct {
	RunID     string `db:"run_id"`
	TaskID    string `db:"task_id"`
	CallID    string `db:"call_id"`
	ToolName  string `db:"tool_name"`
	InputHash string `db:"input_hash"`
	CreatedAt int64  `db:"created_at"`
}
