// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgen

import (
	"context"
	"database/sql"
)

const advanceCacheEpochCAS = `-- name: AdvanceCacheEpochCAS :execresult
UPDATE session_projections SET cache_epoch=cache_epoch+1,cache_identity_hash=? WHERE session_id=? AND cache_epoch=?
`

type AdvanceCacheEpochCASParams struct {
	CacheIdentityHash string `db:"cache_identity_hash"`
	SessionID         string `db:"session_id"`
	CacheEpoch        int64  `db:"cache_epoch"`
}

func (q *Queries) AdvanceCacheEpochCAS(ctx context.Context, arg AdvanceCacheEpochCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, advanceCacheEpochCAS, arg.CacheIdentityHash, arg.SessionID, arg.CacheEpoch)
}

const aggregateCompactionUsage = `-- name: AggregateCompactionUsage :one
SELECT CAST(COALESCE(SUM(input_tokens),0) AS INTEGER) raw_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN input_tokens ELSE 0 END),0) AS INTEGER) reported_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN cached_tokens ELSE 0 END),0) AS INTEGER) cached,CAST(COALESCE(SUM(cache_write_tokens),0) AS INTEGER) cache_write,CAST(COALESCE(SUM(output_tokens),0) AS INTEGER) output,CAST(COALESCE(SUM(reasoning_tokens),0) AS INTEGER) reasoning,CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) total,COUNT(*) requests,CAST(COALESCE(SUM(cache_reported),0) AS INTEGER) reported_requests,CAST(COALESCE(MAX(cache_reported),0) AS INTEGER) reported FROM provider_requests WHERE session_id=? AND status='completed' AND request_kind='compaction'
`

type AggregateCompactionUsageRow struct {
	RawInput         int64 `db:"raw_input"`
	ReportedInput    int64 `db:"reported_input"`
	Cached           int64 `db:"cached"`
	CacheWrite       int64 `db:"cache_write"`
	Output           int64 `db:"output"`
	Reasoning        int64 `db:"reasoning"`
	Total            int64 `db:"total"`
	Requests         int64 `db:"requests"`
	ReportedRequests int64 `db:"reported_requests"`
	Reported         int64 `db:"reported"`
}

func (q *Queries) AggregateCompactionUsage(ctx context.Context, sessionID string) (AggregateCompactionUsageRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateCompactionUsage, sessionID)
	var i AggregateCompactionUsageRow
	err := row.Scan(
		&i.RawInput,
		&i.ReportedInput,
		&i.Cached,
		&i.CacheWrite,
		&i.Output,
		&i.Reasoning,
		&i.Total,
		&i.Requests,
		&i.ReportedRequests,
		&i.Reported,
	)
	return i, err
}

const aggregateMainUsage = `-- name: AggregateMainUsage :one
SELECT CAST(COALESCE(SUM(input_tokens),0) AS INTEGER) raw_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN input_tokens ELSE 0 END),0) AS INTEGER) reported_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN cached_tokens ELSE 0 END),0) AS INTEGER) cached,CAST(COALESCE(SUM(cache_write_tokens),0) AS INTEGER) cache_write,CAST(COALESCE(SUM(output_tokens),0) AS INTEGER) output,CAST(COALESCE(SUM(reasoning_tokens),0) AS INTEGER) reasoning,CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) total,COUNT(*) requests,CAST(COALESCE(SUM(cache_reported),0) AS INTEGER) reported_requests,CAST(COALESCE(MAX(cache_reported),0) AS INTEGER) reported FROM provider_requests WHERE session_id=? AND status='completed' AND request_kind='main'
`

type AggregateMainUsageRow struct {
	RawInput         int64 `db:"raw_input"`
	ReportedInput    int64 `db:"reported_input"`
	Cached           int64 `db:"cached"`
	CacheWrite       int64 `db:"cache_write"`
	Output           int64 `db:"output"`
	Reasoning        int64 `db:"reasoning"`
	Total            int64 `db:"total"`
	Requests         int64 `db:"requests"`
	ReportedRequests int64 `db:"reported_requests"`
	Reported         int64 `db:"reported"`
}

func (q *Queries) AggregateMainUsage(ctx context.Context, sessionID string) (AggregateMainUsageRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateMainUsage, sessionID)
	var i AggregateMainUsageRow
	err := row.Scan(
		&i.RawInput,
		&i.ReportedInput,
		&i.Cached,
		&i.CacheWrite,
		&i.Output,
		&i.Reasoning,
		&i.Total,
		&i.Requests,
		&i.ReportedRequests,
		&i.Reported,
	)
	return i, err
}

const aggregateMainUsageByEpoch = `-- name: AggregateMainUsageByEpoch :one
SELECT CAST(COALESCE(SUM(input_tokens),0) AS INTEGER) raw_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN input_tokens ELSE 0 END),0) AS INTEGER) reported_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN cached_tokens ELSE 0 END),0) AS INTEGER) cached,CAST(COALESCE(SUM(cache_write_tokens),0) AS INTEGER) cache_write,CAST(COALESCE(SUM(output_tokens),0) AS INTEGER) output,CAST(COALESCE(SUM(reasoning_tokens),0) AS INTEGER) reasoning,CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) total,COUNT(*) requests,CAST(COALESCE(SUM(cache_reported),0) AS INTEGER) reported_requests,CAST(COALESCE(MAX(cache_reported),0) AS INTEGER) reported FROM provider_requests WHERE session_id=? AND status='completed' AND request_kind='main' AND cache_epoch=?
`

type AggregateMainUsageByEpochParams struct {
	SessionID  string `db:"session_id"`
	CacheEpoch int64  `db:"cache_epoch"`
}

type AggregateMainUsageByEpochRow struct {
	RawInput         int64 `db:"raw_input"`
	ReportedInput    int64 `db:"reported_input"`
	Cached           int64 `db:"cached"`
	CacheWrite       int64 `db:"cache_write"`
	Output           int64 `db:"output"`
	Reasoning        int64 `db:"reasoning"`
	Total            int64 `db:"total"`
	Requests         int64 `db:"requests"`
	ReportedRequests int64 `db:"reported_requests"`
	Reported         int64 `db:"reported"`
}

func (q *Queries) AggregateMainUsageByEpoch(ctx context.Context, arg AggregateMainUsageByEpochParams) (AggregateMainUsageByEpochRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateMainUsageByEpoch, arg.SessionID, arg.CacheEpoch)
	var i AggregateMainUsageByEpochRow
	err := row.Scan(
		&i.RawInput,
		&i.ReportedInput,
		&i.Cached,
		&i.CacheWrite,
		&i.Output,
		&i.Reasoning,
		&i.Total,
		&i.Requests,
		&i.ReportedRequests,
		&i.Reported,
	)
	return i, err
}

const aggregateMainUsageByRun = `-- name: AggregateMainUsageByRun :one
SELECT CAST(COALESCE(SUM(input_tokens),0) AS INTEGER) raw_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN input_tokens ELSE 0 END),0) AS INTEGER) reported_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN cached_tokens ELSE 0 END),0) AS INTEGER) cached,CAST(COALESCE(SUM(cache_write_tokens),0) AS INTEGER) cache_write,CAST(COALESCE(SUM(output_tokens),0) AS INTEGER) output,CAST(COALESCE(SUM(reasoning_tokens),0) AS INTEGER) reasoning,CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) total,COUNT(*) requests,CAST(COALESCE(SUM(cache_reported),0) AS INTEGER) reported_requests,CAST(COALESCE(MAX(cache_reported),0) AS INTEGER) reported FROM provider_requests WHERE session_id=? AND status='completed' AND request_kind='main' AND run_id=?
`

type AggregateMainUsageByRunParams struct {
	SessionID string `db:"session_id"`
	RunID     string `db:"run_id"`
}

type AggregateMainUsageByRunRow struct {
	RawInput         int64 `db:"raw_input"`
	ReportedInput    int64 `db:"reported_input"`
	Cached           int64 `db:"cached"`
	CacheWrite       int64 `db:"cache_write"`
	Output           int64 `db:"output"`
	Reasoning        int64 `db:"reasoning"`
	Total            int64 `db:"total"`
	Requests         int64 `db:"requests"`
	ReportedRequests int64 `db:"reported_requests"`
	Reported         int64 `db:"reported"`
}

func (q *Queries) AggregateMainUsageByRun(ctx context.Context, arg AggregateMainUsageByRunParams) (AggregateMainUsageByRunRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateMainUsageByRun, arg.SessionID, arg.RunID)
	var i AggregateMainUsageByRunRow
	err := row.Scan(
		&i.RawInput,
		&i.ReportedInput,
		&i.Cached,
		&i.CacheWrite,
		&i.Output,
		&i.Reasoning,
		&i.Total,
		&i.Requests,
		&i.ReportedRequests,
		&i.Reported,
	)
	return i, err
}

const aggregateSubagentUsage = `-- name: AggregateSubagentUsage :one
SELECT CAST(COALESCE(SUM(input_tokens),0) AS INTEGER) raw_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN input_tokens ELSE 0 END),0) AS INTEGER) reported_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN cached_tokens ELSE 0 END),0) AS INTEGER) cached,CAST(COALESCE(SUM(cache_write_tokens),0) AS INTEGER) cache_write,CAST(COALESCE(SUM(output_tokens),0) AS INTEGER) output,CAST(COALESCE(SUM(reasoning_tokens),0) AS INTEGER) reasoning,CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) total,COUNT(*) requests,CAST(COALESCE(SUM(cache_reported),0) AS INTEGER) reported_requests,CAST(COALESCE(MAX(cache_reported),0) AS INTEGER) reported FROM provider_requests WHERE session_id=? AND status='completed' AND request_kind='subagent'
`

type AggregateSubagentUsageRow struct {
	RawInput         int64 `db:"raw_input"`
	ReportedInput    int64 `db:"reported_input"`
	Cached           int64 `db:"cached"`
	CacheWrite       int64 `db:"cache_write"`
	Output           int64 `db:"output"`
	Reasoning        int64 `db:"reasoning"`
	Total            int64 `db:"total"`
	Requests         int64 `db:"requests"`
	ReportedRequests int64 `db:"reported_requests"`
	Reported         int64 `db:"reported"`
}

func (q *Queries) AggregateSubagentUsage(ctx context.Context, sessionID string) (AggregateSubagentUsageRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateSubagentUsage, sessionID)
	var i AggregateSubagentUsageRow
	err := row.Scan(
		&i.RawInput,
		&i.ReportedInput,
		&i.Cached,
		&i.CacheWrite,
		&i.Output,
		&i.Reasoning,
		&i.Total,
		&i.Requests,
		&i.ReportedRequests,
		&i.Reported,
	)
	return i, err
}

const aggregateTeamUsage = `-- name: AggregateTeamUsage :one
SELECT CAST(COALESCE(SUM(input_tokens),0) AS INTEGER) raw_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN input_tokens ELSE 0 END),0) AS INTEGER) reported_input,CAST(COALESCE(SUM(CASE WHEN cache_reported=1 THEN cached_tokens ELSE 0 END),0) AS INTEGER) cached,CAST(COALESCE(SUM(cache_write_tokens),0) AS INTEGER) cache_write,CAST(COALESCE(SUM(output_tokens),0) AS INTEGER) output,CAST(COALESCE(SUM(reasoning_tokens),0) AS INTEGER) reasoning,CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) total,COUNT(*) requests,CAST(COALESCE(SUM(cache_reported),0) AS INTEGER) reported_requests,CAST(COALESCE(MAX(cache_reported),0) AS INTEGER) reported FROM provider_requests WHERE session_id=? AND status='completed' AND request_kind='team'
`

type AggregateTeamUsageRow struct {
	RawInput         int64 `db:"raw_input"`
	ReportedInput    int64 `db:"reported_input"`
	Cached           int64 `db:"cached"`
	CacheWrite       int64 `db:"cache_write"`
	Output           int64 `db:"output"`
	Reasoning        int64 `db:"reasoning"`
	Total            int64 `db:"total"`
	Requests         int64 `db:"requests"`
	ReportedRequests int64 `db:"reported_requests"`
	Reported         int64 `db:"reported"`
}

func (q *Queries) AggregateTeamUsage(ctx context.Context, sessionID string) (AggregateTeamUsageRow, error) {
	row := q.db.QueryRowContext(ctx, aggregateTeamUsage, sessionID)
	var i AggregateTeamUsageRow
	err := row.Scan(
		&i.RawInput,
		&i.ReportedInput,
		&i.Cached,
		&i.CacheWrite,
		&i.Output,
		&i.Reasoning,
		&i.Total,
		&i.Requests,
		&i.ReportedRequests,
		&i.Reported,
	)
	return i, err
}

const canonicalHighWater = `-- name: CanonicalHighWater :one
SELECT sequence FROM session_blocks WHERE session_id=? AND kind IN ('user','assistant') ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) CanonicalHighWater(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, canonicalHighWater, sessionID)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const changeCacheIdentity = `-- name: ChangeCacheIdentity :exec
UPDATE session_projections SET cache_epoch=?,cache_identity_hash=? WHERE session_id=?
`

type ChangeCacheIdentityParams struct {
	CacheEpoch        int64  `db:"cache_epoch"`
	CacheIdentityHash string `db:"cache_identity_hash"`
	SessionID         string `db:"session_id"`
}

func (q *Queries) ChangeCacheIdentity(ctx context.Context, arg ChangeCacheIdentityParams) error {
	_, err := q.db.ExecContext(ctx, changeCacheIdentity, arg.CacheEpoch, arg.CacheIdentityHash, arg.SessionID)
	return err
}

const completeProjectionCAS = `-- name: CompleteProjectionCAS :execresult
UPDATE session_projections SET last_run_id=?,model_history=?,checkpoint_generation=?,updated_at=? WHERE session_id=? AND last_run_id=? AND checkpoint_generation=?
`

type CompleteProjectionCASParams struct {
	LastRunID              string `db:"last_run_id"`
	ModelHistory           []byte `db:"model_history"`
	CheckpointGeneration   int64  `db:"checkpoint_generation"`
	UpdatedAt              int64  `db:"updated_at"`
	SessionID              string `db:"session_id"`
	LastRunID_2            string `db:"last_run_id_2"`
	CheckpointGeneration_2 int64  `db:"checkpoint_generation_2"`
}

func (q *Queries) CompleteProjectionCAS(ctx context.Context, arg CompleteProjectionCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, completeProjectionCAS,
		arg.LastRunID,
		arg.ModelHistory,
		arg.CheckpointGeneration,
		arg.UpdatedAt,
		arg.SessionID,
		arg.LastRunID_2,
		arg.CheckpointGeneration_2,
	)
}

const countToolCallCharges = `-- name: CountToolCallCharges :one
SELECT COUNT(*) FROM tool_call_charges WHERE run_id=? AND task_id=?
`

type CountToolCallChargesParams struct {
	RunID  string `db:"run_id"`
	TaskID string `db:"task_id"`
}

func (q *Queries) CountToolCallCharges(ctx context.Context, arg CountToolCallChargesParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countToolCallCharges, arg.RunID, arg.TaskID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUncheckpointedCompletions = `-- name: CountUncheckpointedCompletions :one
SELECT COUNT(*) FROM provider_requests WHERE session_id=? AND run_id=? AND status='completed' AND checkpoint_generation>=?
`

type CountUncheckpointedCompletionsParams struct {
	SessionID            string `db:"session_id"`
	RunID                string `db:"run_id"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
}

func (q *Queries) CountUncheckpointedCompletions(ctx context.Context, arg CountUncheckpointedCompletionsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUncheckpointedCompletions, arg.SessionID, arg.RunID, arg.CheckpointGeneration)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnknownProviderRequests = `-- name: CountUnknownProviderRequests :one
SELECT COUNT(*) FROM provider_requests WHERE session_id=? AND run_id=? AND status='unknown'
`

type CountUnknownProviderRequestsParams struct {
	SessionID string `db:"session_id"`
	RunID     string `db:"run_id"`
}

func (q *Queries) CountUnknownProviderRequests(ctx context.Context, arg CountUnknownProviderRequestsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnknownProviderRequests, arg.SessionID, arg.RunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSubagentRun = `-- name: CreateSubagentRun :exec
INSERT INTO subagent_runs(id,session_id,parent_run_id,parent_agent_id,tool_call_id,child_run_id,description,subagent_type,state,summary,provider,model,reasoning,capability_mode,requested_isolation,isolation,cwd,background,output,error,warning,transcript,tool_calls,turns,tokens_used,tools_used,worktree_path,completion_delivered,started_at,finished_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)
`

type CreateSubagentRunParams struct {
	ID                  string `db:"id"`
	SessionID           string `db:"session_id"`
	ParentRunID         string `db:"parent_run_id"`
	ParentAgentID       string `db:"parent_agent_id"`
	ToolCallID          string `db:"tool_call_id"`
	ChildRunID          string `db:"child_run_id"`
	Description         string `db:"description"`
	SubagentType        string `db:"subagent_type"`
	State               string `db:"state"`
	Summary             string `db:"summary"`
	Provider            string `db:"provider"`
	Model               string `db:"model"`
	Reasoning           string `db:"reasoning"`
	CapabilityMode      string `db:"capability_mode"`
	RequestedIsolation  string `db:"requested_isolation"`
	Isolation           string `db:"isolation"`
	Cwd                 string `db:"cwd"`
	Background          int64  `db:"background"`
	Output              string `db:"output"`
	Error               string `db:"error"`
	Warning             string `db:"warning"`
	Transcript          []byte `db:"transcript"`
	ToolCalls           int64  `db:"tool_calls"`
	Turns               int64  `db:"turns"`
	TokensUsed          int64  `db:"tokens_used"`
	ToolsUsed           []byte `db:"tools_used"`
	WorktreePath        string `db:"worktree_path"`
	CompletionDelivered int64  `db:"completion_delivered"`
	StartedAt           int64  `db:"started_at"`
	FinishedAt          int64  `db:"finished_at"`
}

func (q *Queries) CreateSubagentRun(ctx context.Context, arg CreateSubagentRunParams) error {
	_, err := q.db.ExecContext(ctx, createSubagentRun,
		arg.ID,
		arg.SessionID,
		arg.ParentRunID,
		arg.ParentAgentID,
		arg.ToolCallID,
		arg.ChildRunID,
		arg.Description,
		arg.SubagentType,
		arg.State,
		arg.Summary,
		arg.Provider,
		arg.Model,
		arg.Reasoning,
		arg.CapabilityMode,
		arg.RequestedIsolation,
		arg.Isolation,
		arg.Cwd,
		arg.Background,
		arg.Output,
		arg.Error,
		arg.Warning,
		arg.Transcript,
		arg.ToolCalls,
		arg.Turns,
		arg.TokensUsed,
		arg.ToolsUsed,
		arg.WorktreePath,
		arg.CompletionDelivered,
		arg.StartedAt,
		arg.FinishedAt,
	)
	return err
}

const deleteCatalog = `-- name: DeleteCatalog :exec
DELETE FROM model_catalog WHERE provider_id=? AND account_id=?
`

type DeleteCatalogParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
}

func (q *Queries) DeleteCatalog(ctx context.Context, arg DeleteCatalogParams) error {
	_, err := q.db.ExecContext(ctx, deleteCatalog, arg.ProviderID, arg.AccountID)
	return err
}

const deleteCredential = `-- name: DeleteCredential :exec
DELETE FROM auth_credentials WHERE provider_id=? AND account_id=?
`

type DeleteCredentialParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
}

func (q *Queries) DeleteCredential(ctx context.Context, arg DeleteCredentialParams) error {
	_, err := q.db.ExecContext(ctx, deleteCredential, arg.ProviderID, arg.AccountID)
	return err
}

const ensureSession = `-- name: EnsureSession :exec
INSERT INTO sessions(id,title,provider_id,model_id,reasoning,agent_mode,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO NOTHING
`

type EnsureSessionParams struct {
	ID         string `db:"id"`
	Title      string `db:"title"`
	ProviderID string `db:"provider_id"`
	ModelID    string `db:"model_id"`
	Reasoning  string `db:"reasoning"`
	AgentMode  string `db:"agent_mode"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

func (q *Queries) EnsureSession(ctx context.Context, arg EnsureSessionParams) error {
	_, err := q.db.ExecContext(ctx, ensureSession,
		arg.ID,
		arg.Title,
		arg.ProviderID,
		arg.ModelID,
		arg.Reasoning,
		arg.AgentMode,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const ensureSessionProjection = `-- name: EnsureSessionProjection :exec
INSERT INTO session_projections(session_id,updated_at) VALUES(?,?) ON CONFLICT(session_id) DO NOTHING
`

type EnsureSessionProjectionParams struct {
	SessionID string `db:"session_id"`
	UpdatedAt int64  `db:"updated_at"`
}

func (q *Queries) EnsureSessionProjection(ctx context.Context, arg EnsureSessionProjectionParams) error {
	_, err := q.db.ExecContext(ctx, ensureSessionProjection, arg.SessionID, arg.UpdatedAt)
	return err
}

const expireActiveLeaseCAS = `-- name: ExpireActiveLeaseCAS :execresult
UPDATE leases SET status=?,data=? WHERE id=? AND version=? AND status=?
`

type ExpireActiveLeaseCASParams struct {
	Status   string `db:"status"`
	Data     []byte `db:"data"`
	ID       string `db:"id"`
	Version  int64  `db:"version"`
	Status_2 string `db:"status_2"`
}

func (q *Queries) ExpireActiveLeaseCAS(ctx context.Context, arg ExpireActiveLeaseCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, expireActiveLeaseCAS,
		arg.Status,
		arg.Data,
		arg.ID,
		arg.Version,
		arg.Status_2,
	)
}

const expireLeaseCAS = `-- name: ExpireLeaseCAS :execresult
UPDATE leases SET status=?,data=? WHERE id=? AND version=?
`

type ExpireLeaseCASParams struct {
	Status  string `db:"status"`
	Data    []byte `db:"data"`
	ID      string `db:"id"`
	Version int64  `db:"version"`
}

func (q *Queries) ExpireLeaseCAS(ctx context.Context, arg ExpireLeaseCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, expireLeaseCAS,
		arg.Status,
		arg.Data,
		arg.ID,
		arg.Version,
	)
}

const extendCatalog = `-- name: ExtendCatalog :exec
UPDATE model_catalog SET expires_at=? WHERE provider_id=? AND account_id=?
`

type ExtendCatalogParams struct {
	ExpiresAt  int64  `db:"expires_at"`
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
}

func (q *Queries) ExtendCatalog(ctx context.Context, arg ExtendCatalogParams) error {
	_, err := q.db.ExecContext(ctx, extendCatalog, arg.ExpiresAt, arg.ProviderID, arg.AccountID)
	return err
}

const extendLeaseCAS = `-- name: ExtendLeaseCAS :execresult
UPDATE leases SET expires_at=?,version=?,data=? WHERE id=? AND holder_id=? AND status=? AND version=?
`

type ExtendLeaseCASParams struct {
	ExpiresAt int64  `db:"expires_at"`
	Version   int64  `db:"version"`
	Data      []byte `db:"data"`
	ID        string `db:"id"`
	HolderID  string `db:"holder_id"`
	Status    string `db:"status"`
	Version_2 int64  `db:"version_2"`
}

func (q *Queries) ExtendLeaseCAS(ctx context.Context, arg ExtendLeaseCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, extendLeaseCAS,
		arg.ExpiresAt,
		arg.Version,
		arg.Data,
		arg.ID,
		arg.HolderID,
		arg.Status,
		arg.Version_2,
	)
}

const forgetMemory = `-- name: ForgetMemory :execresult
UPDATE memories SET status='forgotten',updated_at=? WHERE id=? AND anchor=? AND status='active'
`

type ForgetMemoryParams struct {
	UpdatedAt int64  `db:"updated_at"`
	ID        string `db:"id"`
	Anchor    string `db:"anchor"`
}

func (q *Queries) ForgetMemory(ctx context.Context, arg ForgetMemoryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, forgetMemory, arg.UpdatedAt, arg.ID, arg.Anchor)
}

const getAccount = `-- name: GetAccount :one
SELECT id,provider_id,email,display_name,plan,credential_ref,status,created_at,updated_at FROM accounts WHERE provider_id=? AND id=?
`

type GetAccountParams struct {
	ProviderID string `db:"provider_id"`
	ID         string `db:"id"`
}

func (q *Queries) GetAccount(ctx context.Context, arg GetAccountParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccount, arg.ProviderID, arg.ID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.ProviderID,
		&i.Email,
		&i.DisplayName,
		&i.Plan,
		&i.CredentialRef,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActionAttemptByIdempotency = `-- name: GetActionAttemptByIdempotency :one
SELECT data FROM records WHERE kind=? AND run_id=? AND task_id=? AND tool_name=? AND idempotency_key=?
`

type GetActionAttemptByIdempotencyParams struct {
	Kind           string `db:"kind"`
	RunID          string `db:"run_id"`
	TaskID         string `db:"task_id"`
	ToolName       string `db:"tool_name"`
	IdempotencyKey string `db:"idempotency_key"`
}

func (q *Queries) GetActionAttemptByIdempotency(ctx context.Context, arg GetActionAttemptByIdempotencyParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getActionAttemptByIdempotency,
		arg.Kind,
		arg.RunID,
		arg.TaskID,
		arg.ToolName,
		arg.IdempotencyKey,
	)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getCacheEpoch = `-- name: GetCacheEpoch :one
SELECT cache_epoch FROM session_projections WHERE session_id=?
`

func (q *Queries) GetCacheEpoch(ctx context.Context, sessionID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, getCacheEpoch, sessionID)
	var cache_epoch int64
	err := row.Scan(&cache_epoch)
	return cache_epoch, err
}

const getCacheProjection = `-- name: GetCacheProjection :one
SELECT cache_epoch,checkpoint_generation,cache_identity_hash FROM session_projections WHERE session_id=?
`

type GetCacheProjectionRow struct {
	CacheEpoch           int64  `db:"cache_epoch"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	CacheIdentityHash    string `db:"cache_identity_hash"`
}

func (q *Queries) GetCacheProjection(ctx context.Context, sessionID string) (GetCacheProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, getCacheProjection, sessionID)
	var i GetCacheProjectionRow
	err := row.Scan(&i.CacheEpoch, &i.CheckpointGeneration, &i.CacheIdentityHash)
	return i, err
}

const getCatalogETag = `-- name: GetCatalogETag :one
SELECT etag FROM model_catalog WHERE provider_id=? AND account_id=? LIMIT 1
`

type GetCatalogETagParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
}

func (q *Queries) GetCatalogETag(ctx context.Context, arg GetCatalogETagParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCatalogETag, arg.ProviderID, arg.AccountID)
	var etag string
	err := row.Scan(&etag)
	return etag, err
}

const getCompactionState = `-- name: GetCompactionState :one
SELECT model_history,updated_at,checkpoint_generation,cache_epoch FROM session_projections WHERE session_id=?
`

type GetCompactionStateRow struct {
	ModelHistory         []byte `db:"model_history"`
	UpdatedAt            int64  `db:"updated_at"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	CacheEpoch           int64  `db:"cache_epoch"`
}

func (q *Queries) GetCompactionState(ctx context.Context, sessionID string) (GetCompactionStateRow, error) {
	row := q.db.QueryRowContext(ctx, getCompactionState, sessionID)
	var i GetCompactionStateRow
	err := row.Scan(
		&i.ModelHistory,
		&i.UpdatedAt,
		&i.CheckpointGeneration,
		&i.CacheEpoch,
	)
	return i, err
}

const getContextArtifact = `-- name: GetContextArtifact :one
SELECT id,session_id,run_id,kind,sha256,payload,preview,created_at FROM context_artifacts WHERE id=? AND session_id=?
`

type GetContextArtifactParams struct {
	ID        string `db:"id"`
	SessionID string `db:"session_id"`
}

func (q *Queries) GetContextArtifact(ctx context.Context, arg GetContextArtifactParams) (ContextArtifact, error) {
	row := q.db.QueryRowContext(ctx, getContextArtifact, arg.ID, arg.SessionID)
	var i ContextArtifact
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.RunID,
		&i.Kind,
		&i.Sha256,
		&i.Payload,
		&i.Preview,
		&i.CreatedAt,
	)
	return i, err
}

const getCredential = `-- name: GetCredential :one
SELECT data FROM auth_credentials WHERE provider_id=? AND account_id=?
`

type GetCredentialParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
}

func (q *Queries) GetCredential(ctx context.Context, arg GetCredentialParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCredential, arg.ProviderID, arg.AccountID)
	var data string
	err := row.Scan(&data)
	return data, err
}

const getCredentialRef = `-- name: GetCredentialRef :one
SELECT credential_ref FROM accounts WHERE provider_id=? AND id=?
`

type GetCredentialRefParams struct {
	ProviderID string `db:"provider_id"`
	ID         string `db:"id"`
}

func (q *Queries) GetCredentialRef(ctx context.Context, arg GetCredentialRefParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getCredentialRef, arg.ProviderID, arg.ID)
	var credential_ref string
	err := row.Scan(&credential_ref)
	return credential_ref, err
}

const getLatestLease = `-- name: GetLatestLease :one
SELECT version,data FROM leases WHERE run_id=? AND task_id=? ORDER BY version DESC LIMIT 1
`

type GetLatestLeaseParams struct {
	RunID  string `db:"run_id"`
	TaskID string `db:"task_id"`
}

type GetLatestLeaseRow struct {
	Version int64  `db:"version"`
	Data    []byte `db:"data"`
}

func (q *Queries) GetLatestLease(ctx context.Context, arg GetLatestLeaseParams) (GetLatestLeaseRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestLease, arg.RunID, arg.TaskID)
	var i GetLatestLeaseRow
	err := row.Scan(&i.Version, &i.Data)
	return i, err
}

const getLatestLeaseData = `-- name: GetLatestLeaseData :one
SELECT data FROM leases WHERE run_id=? AND task_id=? ORDER BY version DESC LIMIT 1
`

type GetLatestLeaseDataParams struct {
	RunID  string `db:"run_id"`
	TaskID string `db:"task_id"`
}

func (q *Queries) GetLatestLeaseData(ctx context.Context, arg GetLatestLeaseDataParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLatestLeaseData, arg.RunID, arg.TaskID)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getLatestSessionBlock = `-- name: GetLatestSessionBlock :one
SELECT sequence,data FROM session_blocks WHERE session_id=? ORDER BY sequence DESC LIMIT 1
`

type GetLatestSessionBlockRow struct {
	Sequence int64  `db:"sequence"`
	Data     []byte `db:"data"`
}

func (q *Queries) GetLatestSessionBlock(ctx context.Context, sessionID string) (GetLatestSessionBlockRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestSessionBlock, sessionID)
	var i GetLatestSessionBlockRow
	err := row.Scan(&i.Sequence, &i.Data)
	return i, err
}

const getLeaseData = `-- name: GetLeaseData :one
SELECT data FROM leases WHERE id=?
`

func (q *Queries) GetLeaseData(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLeaseData, id)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getProjectionCheckpoint = `-- name: GetProjectionCheckpoint :one
SELECT last_run_id,checkpoint_generation FROM session_projections WHERE session_id=?
`

type GetProjectionCheckpointRow struct {
	LastRunID            string `db:"last_run_id"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
}

func (q *Queries) GetProjectionCheckpoint(ctx context.Context, sessionID string) (GetProjectionCheckpointRow, error) {
	row := q.db.QueryRowContext(ctx, getProjectionCheckpoint, sessionID)
	var i GetProjectionCheckpointRow
	err := row.Scan(&i.LastRunID, &i.CheckpointGeneration)
	return i, err
}

const getProjectionHistory = `-- name: GetProjectionHistory :one
SELECT model_history FROM session_projections WHERE session_id=?
`

func (q *Queries) GetProjectionHistory(ctx context.Context, sessionID string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getProjectionHistory, sessionID)
	var model_history []byte
	err := row.Scan(&model_history)
	return model_history, err
}

const getRecap = `-- name: GetRecap :one
SELECT session_id,anchor,covered_boundary,revision,goal,summary,open_items,updated_at FROM recaps WHERE session_id=? AND anchor=?
`

type GetRecapParams struct {
	SessionID string `db:"session_id"`
	Anchor    string `db:"anchor"`
}

func (q *Queries) GetRecap(ctx context.Context, arg GetRecapParams) (Recap, error) {
	row := q.db.QueryRowContext(ctx, getRecap, arg.SessionID, arg.Anchor)
	var i Recap
	err := row.Scan(
		&i.SessionID,
		&i.Anchor,
		&i.CoveredBoundary,
		&i.Revision,
		&i.Goal,
		&i.Summary,
		&i.OpenItems,
		&i.UpdatedAt,
	)
	return i, err
}

const getReconcileAttemptData = `-- name: GetReconcileAttemptData :one
SELECT data FROM records WHERE kind=? AND key1=? AND status=?
`

type GetReconcileAttemptDataParams struct {
	Kind   string `db:"kind"`
	Key1   string `db:"key1"`
	Status string `db:"status"`
}

func (q *Queries) GetReconcileAttemptData(ctx context.Context, arg GetReconcileAttemptDataParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getReconcileAttemptData, arg.Kind, arg.Key1, arg.Status)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getRecordData = `-- name: GetRecordData :one
SELECT data FROM records WHERE kind=? AND key1=? AND key2=?
`

type GetRecordDataParams struct {
	Kind string `db:"kind"`
	Key1 string `db:"key1"`
	Key2 string `db:"key2"`
}

func (q *Queries) GetRecordData(ctx context.Context, arg GetRecordDataParams) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getRecordData, arg.Kind, arg.Key1, arg.Key2)
	var data []byte
	err := row.Scan(&data)
	return data, err
}

const getRunCheckpointState = `-- name: GetRunCheckpointState :one
SELECT last_run_id,checkpoint_generation,cache_epoch,cache_identity_hash FROM session_projections WHERE session_id=?
`

type GetRunCheckpointStateRow struct {
	LastRunID            string `db:"last_run_id"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	CacheEpoch           int64  `db:"cache_epoch"`
	CacheIdentityHash    string `db:"cache_identity_hash"`
}

func (q *Queries) GetRunCheckpointState(ctx context.Context, sessionID string) (GetRunCheckpointStateRow, error) {
	row := q.db.QueryRowContext(ctx, getRunCheckpointState, sessionID)
	var i GetRunCheckpointStateRow
	err := row.Scan(
		&i.LastRunID,
		&i.CheckpointGeneration,
		&i.CacheEpoch,
		&i.CacheIdentityHash,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id,title,provider_id,model_id,reasoning,agent_mode,created_at,updated_at FROM sessions WHERE id=?
`

func (q *Queries) GetSession(ctx context.Context, id string) (Session, error) {
	row := q.db.QueryRowContext(ctx, getSession, id)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.ProviderID,
		&i.ModelID,
		&i.Reasoning,
		&i.AgentMode,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionProjection = `-- name: GetSessionProjection :one
SELECT last_run_id,blocks,model_history,usage,updated_at,checkpoint_generation,cache_epoch,cache_identity_hash FROM session_projections WHERE session_id=?
`

type GetSessionProjectionRow struct {
	LastRunID            string `db:"last_run_id"`
	Blocks               []byte `db:"blocks"`
	ModelHistory         []byte `db:"model_history"`
	Usage                []byte `db:"usage"`
	UpdatedAt            int64  `db:"updated_at"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	CacheEpoch           int64  `db:"cache_epoch"`
	CacheIdentityHash    string `db:"cache_identity_hash"`
}

func (q *Queries) GetSessionProjection(ctx context.Context, sessionID string) (GetSessionProjectionRow, error) {
	row := q.db.QueryRowContext(ctx, getSessionProjection, sessionID)
	var i GetSessionProjectionRow
	err := row.Scan(
		&i.LastRunID,
		&i.Blocks,
		&i.ModelHistory,
		&i.Usage,
		&i.UpdatedAt,
		&i.CheckpointGeneration,
		&i.CacheEpoch,
		&i.CacheIdentityHash,
	)
	return i, err
}

const getSubagentRun = `-- name: GetSubagentRun :one
SELECT id, session_id, parent_run_id, parent_agent_id, tool_call_id, child_run_id, description, subagent_type, state, summary, provider, model, reasoning, capability_mode, requested_isolation, isolation, cwd, background, output, error, warning, transcript, tool_calls, turns, tokens_used, tools_used, worktree_path, completion_delivered, started_at, finished_at FROM subagent_runs WHERE id=?
`

func (q *Queries) GetSubagentRun(ctx context.Context, id string) (SubagentRun, error) {
	row := q.db.QueryRowContext(ctx, getSubagentRun, id)
	var i SubagentRun
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.ParentRunID,
		&i.ParentAgentID,
		&i.ToolCallID,
		&i.ChildRunID,
		&i.Description,
		&i.SubagentType,
		&i.State,
		&i.Summary,
		&i.Provider,
		&i.Model,
		&i.Reasoning,
		&i.CapabilityMode,
		&i.RequestedIsolation,
		&i.Isolation,
		&i.Cwd,
		&i.Background,
		&i.Output,
		&i.Error,
		&i.Warning,
		&i.Transcript,
		&i.ToolCalls,
		&i.Turns,
		&i.TokensUsed,
		&i.ToolsUsed,
		&i.WorktreePath,
		&i.CompletionDelivered,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getTodo = `-- name: GetTodo :one
SELECT goal,revision,phases,updated_at FROM session_todos WHERE session_id=?
`

type GetTodoRow struct {
	Goal      string `db:"goal"`
	Revision  int64  `db:"revision"`
	Phases    []byte `db:"phases"`
	UpdatedAt int64  `db:"updated_at"`
}

func (q *Queries) GetTodo(ctx context.Context, sessionID string) (GetTodoRow, error) {
	row := q.db.QueryRowContext(ctx, getTodo, sessionID)
	var i GetTodoRow
	err := row.Scan(
		&i.Goal,
		&i.Revision,
		&i.Phases,
		&i.UpdatedAt,
	)
	return i, err
}

const getToolCallCharge = `-- name: GetToolCallCharge :one
SELECT tool_name,input_hash FROM tool_call_charges WHERE run_id=? AND task_id=? AND call_id=?
`

type GetToolCallChargeParams struct {
	RunID  string `db:"run_id"`
	TaskID string `db:"task_id"`
	CallID string `db:"call_id"`
}

type GetToolCallChargeRow struct {
	ToolName  string `db:"tool_name"`
	InputHash string `db:"input_hash"`
}

func (q *Queries) GetToolCallCharge(ctx context.Context, arg GetToolCallChargeParams) (GetToolCallChargeRow, error) {
	row := q.db.QueryRowContext(ctx, getToolCallCharge, arg.RunID, arg.TaskID, arg.CallID)
	var i GetToolCallChargeRow
	err := row.Scan(&i.ToolName, &i.InputHash)
	return i, err
}

const hasActiveChatGPTAccount = `-- name: HasActiveChatGPTAccount :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE provider_id='chatgpt' AND status='active')
`

func (q *Queries) HasActiveChatGPTAccount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasActiveChatGPTAccount)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hasAnyAccount = `-- name: HasAnyAccount :one
SELECT EXISTS(SELECT 1 FROM accounts WHERE provider_id=? LIMIT 1)
`

func (q *Queries) HasAnyAccount(ctx context.Context, providerID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, hasAnyAccount, providerID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const initializeCacheIdentity = `-- name: InitializeCacheIdentity :exec
UPDATE session_projections SET cache_identity_hash=? WHERE session_id=?
`

type InitializeCacheIdentityParams struct {
	CacheIdentityHash string `db:"cache_identity_hash"`
	SessionID         string `db:"session_id"`
}

func (q *Queries) InitializeCacheIdentity(ctx context.Context, arg InitializeCacheIdentityParams) error {
	_, err := q.db.ExecContext(ctx, initializeCacheIdentity, arg.CacheIdentityHash, arg.SessionID)
	return err
}

const insertCatalogModel = `-- name: InsertCatalogModel :exec
INSERT INTO model_catalog(provider_id,account_id,model_id,etag,fetched_at,expires_at,data) VALUES(?,?,?,?,?,?,?)
`

type InsertCatalogModelParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
	ModelID    string `db:"model_id"`
	Etag       string `db:"etag"`
	FetchedAt  int64  `db:"fetched_at"`
	ExpiresAt  int64  `db:"expires_at"`
	Data       []byte `db:"data"`
}

func (q *Queries) InsertCatalogModel(ctx context.Context, arg InsertCatalogModelParams) error {
	_, err := q.db.ExecContext(ctx, insertCatalogModel,
		arg.ProviderID,
		arg.AccountID,
		arg.ModelID,
		arg.Etag,
		arg.FetchedAt,
		arg.ExpiresAt,
		arg.Data,
	)
	return err
}

const insertContextArtifact = `-- name: InsertContextArtifact :exec
INSERT INTO context_artifacts(id,session_id,run_id,kind,sha256,payload,preview,created_at) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(session_id,kind,sha256) DO NOTHING
`

type InsertContextArtifactParams struct {
	ID        string `db:"id"`
	SessionID string `db:"session_id"`
	RunID     string `db:"run_id"`
	Kind      string `db:"kind"`
	Sha256    string `db:"sha256"`
	Payload   []byte `db:"payload"`
	Preview   string `db:"preview"`
	CreatedAt int64  `db:"created_at"`
}

func (q *Queries) InsertContextArtifact(ctx context.Context, arg InsertContextArtifactParams) error {
	_, err := q.db.ExecContext(ctx, insertContextArtifact,
		arg.ID,
		arg.SessionID,
		arg.RunID,
		arg.Kind,
		arg.Sha256,
		arg.Payload,
		arg.Preview,
		arg.CreatedAt,
	)
	return err
}

const insertEvent = `-- name: InsertEvent :exec
INSERT INTO events(run_id,sequence,recorded_at,data) VALUES(?,?,?,?)
`

type InsertEventParams struct {
	RunID      string `db:"run_id"`
	Sequence   int64  `db:"sequence"`
	RecordedAt int64  `db:"recorded_at"`
	Data       []byte `db:"data"`
}

func (q *Queries) InsertEvent(ctx context.Context, arg InsertEventParams) error {
	_, err := q.db.ExecContext(ctx, insertEvent,
		arg.RunID,
		arg.Sequence,
		arg.RecordedAt,
		arg.Data,
	)
	return err
}

const insertLease = `-- name: InsertLease :exec
INSERT INTO leases(id,run_id,task_id,holder_id,status,expires_at,version,data) VALUES(?,?,?,?,?,?,?,?)
`

type InsertLeaseParams struct {
	ID        string `db:"id"`
	RunID     string `db:"run_id"`
	TaskID    string `db:"task_id"`
	HolderID  string `db:"holder_id"`
	Status    string `db:"status"`
	ExpiresAt int64  `db:"expires_at"`
	Version   int64  `db:"version"`
	Data      []byte `db:"data"`
}

func (q *Queries) InsertLease(ctx context.Context, arg InsertLeaseParams) error {
	_, err := q.db.ExecContext(ctx, insertLease,
		arg.ID,
		arg.RunID,
		arg.TaskID,
		arg.HolderID,
		arg.Status,
		arg.ExpiresAt,
		arg.Version,
		arg.Data,
	)
	return err
}

const insertMemory = `-- name: InsertMemory :exec
INSERT INTO memories(id,content,anchor,session_id,provenance,status,importance,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)
`

type InsertMemoryParams struct {
	ID         string `db:"id"`
	Content    string `db:"content"`
	Anchor     string `db:"anchor"`
	SessionID  string `db:"session_id"`
	Provenance string `db:"provenance"`
	Status     string `db:"status"`
	Importance int64  `db:"importance"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

func (q *Queries) InsertMemory(ctx context.Context, arg InsertMemoryParams) error {
	_, err := q.db.ExecContext(ctx, insertMemory,
		arg.ID,
		arg.Content,
		arg.Anchor,
		arg.SessionID,
		arg.Provenance,
		arg.Status,
		arg.Importance,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const insertRecord = `-- name: InsertRecord :exec
INSERT INTO records(kind,key1,key2,run_id,task_id,status,created_at,tool_name,idempotency_key,data) VALUES(?,?,?,?,?,?,?,?,?,?)
`

type InsertRecordParams struct {
	Kind           string `db:"kind"`
	Key1           string `db:"key1"`
	Key2           string `db:"key2"`
	RunID          string `db:"run_id"`
	TaskID         string `db:"task_id"`
	Status         string `db:"status"`
	CreatedAt      int64  `db:"created_at"`
	ToolName       string `db:"tool_name"`
	IdempotencyKey string `db:"idempotency_key"`
	Data           []byte `db:"data"`
}

func (q *Queries) InsertRecord(ctx context.Context, arg InsertRecordParams) error {
	_, err := q.db.ExecContext(ctx, insertRecord,
		arg.Kind,
		arg.Key1,
		arg.Key2,
		arg.RunID,
		arg.TaskID,
		arg.Status,
		arg.CreatedAt,
		arg.ToolName,
		arg.IdempotencyKey,
		arg.Data,
	)
	return err
}

const insertSessionBlock = `-- name: InsertSessionBlock :exec
INSERT INTO session_blocks(session_id,sequence,kind,run_id,agent_id,data) SELECT ?,COALESCE(MAX(b.sequence)+1,0),?,?,?,? FROM session_blocks b WHERE b.session_id=?
`

type InsertSessionBlockParams struct {
	SessionID   string `db:"session_id"`
	Kind        string `db:"kind"`
	RunID       string `db:"run_id"`
	AgentID     string `db:"agent_id"`
	Data        []byte `db:"data"`
	SessionID_2 string `db:"session_id_2"`
}

func (q *Queries) InsertSessionBlock(ctx context.Context, arg InsertSessionBlockParams) error {
	_, err := q.db.ExecContext(ctx, insertSessionBlock,
		arg.SessionID,
		arg.Kind,
		arg.RunID,
		arg.AgentID,
		arg.Data,
		arg.SessionID_2,
	)
	return err
}

const insertTodoIfAbsent = `-- name: InsertTodoIfAbsent :execresult
INSERT INTO session_todos(session_id,goal,revision,phases,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(session_id) DO NOTHING
`

type InsertTodoIfAbsentParams struct {
	SessionID string `db:"session_id"`
	Goal      string `db:"goal"`
	Revision  int64  `db:"revision"`
	Phases    []byte `db:"phases"`
	UpdatedAt int64  `db:"updated_at"`
}

func (q *Queries) InsertTodoIfAbsent(ctx context.Context, arg InsertTodoIfAbsentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertTodoIfAbsent,
		arg.SessionID,
		arg.Goal,
		arg.Revision,
		arg.Phases,
		arg.UpdatedAt,
	)
}

const insertToolCallCharge = `-- name: InsertToolCallCharge :execresult
INSERT OR IGNORE INTO tool_call_charges(run_id,task_id,call_id,tool_name,input_hash,created_at) VALUES(?,?,?,?,?,?)
`

type InsertToolCallChargeParams struct {
	RunID     string `db:"run_id"`
	TaskID    string `db:"task_id"`
	CallID    string `db:"call_id"`
	ToolName  string `db:"tool_name"`
	InputHash string `db:"input_hash"`
	CreatedAt int64  `db:"created_at"`
}

func (q *Queries) InsertToolCallCharge(ctx context.Context, arg InsertToolCallChargeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, insertToolCallCharge,
		arg.RunID,
		arg.TaskID,
		arg.CallID,
		arg.ToolName,
		arg.InputHash,
		arg.CreatedAt,
	)
}

const interruptIncompleteSubagents = `-- name: InterruptIncompleteSubagents :execresult
UPDATE subagent_runs SET state='interrupted',summary='interrupted by process restart',error='interrupted by process restart',finished_at=? WHERE state IN ('initializing','queued','running','cancelling')
`

func (q *Queries) InterruptIncompleteSubagents(ctx context.Context, finishedAt int64) (sql.Result, error) {
	return q.db.ExecContext(ctx, interruptIncompleteSubagents, finishedAt)
}

const latestEventSequence = `-- name: LatestEventSequence :one
SELECT sequence FROM events WHERE run_id=? ORDER BY sequence DESC LIMIT 1
`

func (q *Queries) LatestEventSequence(ctx context.Context, runID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, latestEventSequence, runID)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const latestMainUsage = `-- name: LatestMainUsage :one
SELECT input_tokens,output_tokens FROM provider_requests WHERE session_id=? AND run_id=? AND request_kind='main' AND status='completed' ORDER BY completed_at DESC,started_at DESC,request_id DESC LIMIT 1
`

type LatestMainUsageParams struct {
	SessionID string `db:"session_id"`
	RunID     string `db:"run_id"`
}

type LatestMainUsageRow struct {
	InputTokens  int64 `db:"input_tokens"`
	OutputTokens int64 `db:"output_tokens"`
}

func (q *Queries) LatestMainUsage(ctx context.Context, arg LatestMainUsageParams) (LatestMainUsageRow, error) {
	row := q.db.QueryRowContext(ctx, latestMainUsage, arg.SessionID, arg.RunID)
	var i LatestMainUsageRow
	err := row.Scan(&i.InputTokens, &i.OutputTokens)
	return i, err
}

const listAccounts = `-- name: ListAccounts :many
SELECT id,provider_id,email,display_name,plan,credential_ref,status,created_at,updated_at FROM accounts ORDER BY updated_at DESC
`

func (q *Queries) ListAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Email,
			&i.DisplayName,
			&i.Plan,
			&i.CredentialRef,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountsByProvider = `-- name: ListAccountsByProvider :many
SELECT id,provider_id,email,display_name,plan,credential_ref,status,created_at,updated_at FROM accounts WHERE provider_id=? ORDER BY updated_at DESC
`

func (q *Queries) ListAccountsByProvider(ctx context.Context, providerID string) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, listAccountsByProvider, providerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Account
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.ID,
			&i.ProviderID,
			&i.Email,
			&i.DisplayName,
			&i.Plan,
			&i.CredentialRef,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveLeases = `-- name: ListActiveLeases :many
SELECT id,version,data FROM leases WHERE status=?
`

type ListActiveLeasesRow struct {
	ID      string `db:"id"`
	Version int64  `db:"version"`
	Data    []byte `db:"data"`
}

func (q *Queries) ListActiveLeases(ctx context.Context, status string) ([]ListActiveLeasesRow, error) {
	rows, err := q.db.QueryContext(ctx, listActiveLeases, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListActiveLeasesRow
	for rows.Next() {
		var i ListActiveLeasesRow
		if err := rows.Scan(&i.ID, &i.Version, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCatalog = `-- name: ListCatalog :many
SELECT fetched_at,expires_at,data FROM model_catalog WHERE provider_id=? AND account_id=? ORDER BY model_id
`

type ListCatalogParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
}

type ListCatalogRow struct {
	FetchedAt int64  `db:"fetched_at"`
	ExpiresAt int64  `db:"expires_at"`
	Data      []byte `db:"data"`
}

func (q *Queries) ListCatalog(ctx context.Context, arg ListCatalogParams) ([]ListCatalogRow, error) {
	rows, err := q.db.QueryContext(ctx, listCatalog, arg.ProviderID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCatalogRow
	for rows.Next() {
		var i ListCatalogRow
		if err := rows.Scan(&i.FetchedAt, &i.ExpiresAt, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventData = `-- name: ListEventData :many
SELECT data FROM events WHERE run_id=? ORDER BY sequence
`

func (q *Queries) ListEventData(ctx context.Context, runID string) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listEventData, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEventDataAfter = `-- name: ListEventDataAfter :many
SELECT data FROM events WHERE run_id=? AND sequence>? ORDER BY sequence
`

type ListEventDataAfterParams struct {
	RunID    string `db:"run_id"`
	Sequence int64  `db:"sequence"`
}

func (q *Queries) ListEventDataAfter(ctx context.Context, arg ListEventDataAfterParams) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listEventDataAfter, arg.RunID, arg.Sequence)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIncompleteActionAttempts = `-- name: ListIncompleteActionAttempts :many
SELECT key1,data FROM records WHERE kind=? AND status IN (?,?)
`

type ListIncompleteActionAttemptsParams struct {
	Kind     string `db:"kind"`
	Status   string `db:"status"`
	Status_2 string `db:"status_2"`
}

type ListIncompleteActionAttemptsRow struct {
	Key1 string `db:"key1"`
	Data []byte `db:"data"`
}

func (q *Queries) ListIncompleteActionAttempts(ctx context.Context, arg ListIncompleteActionAttemptsParams) ([]ListIncompleteActionAttemptsRow, error) {
	rows, err := q.db.QueryContext(ctx, listIncompleteActionAttempts, arg.Kind, arg.Status, arg.Status_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncompleteActionAttemptsRow
	for rows.Next() {
		var i ListIncompleteActionAttemptsRow
		if err := rows.Scan(&i.Key1, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMemoriesByContent = `-- name: ListMemoriesByContent :many
SELECT id,content,anchor,session_id,provenance,status,importance,created_at,updated_at FROM memories WHERE anchor=?1 AND status='active' AND instr(lower(content),lower(?2))>0 ORDER BY importance DESC,updated_at DESC LIMIT ?3
`

type ListMemoriesByContentParams struct {
	Anchor  string `db:"anchor"`
	Content string `db:"content"`
	Limit   int64  `db:"limit"`
}

type ListMemoriesByContentRow struct {
	ID         string `db:"id"`
	Content    string `db:"content"`
	Anchor     string `db:"anchor"`
	SessionID  string `db:"session_id"`
	Provenance string `db:"provenance"`
	Status     string `db:"status"`
	Importance int64  `db:"importance"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

func (q *Queries) ListMemoriesByContent(ctx context.Context, arg ListMemoriesByContentParams) ([]ListMemoriesByContentRow, error) {
	rows, err := q.db.QueryContext(ctx, listMemoriesByContent, arg.Anchor, arg.Content, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMemoriesByContentRow
	for rows.Next() {
		var i ListMemoriesByContentRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Anchor,
			&i.SessionID,
			&i.Provenance,
			&i.Status,
			&i.Importance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMemories = `-- name: ListRecentMemories :many
SELECT id,content,anchor,session_id,provenance,status,importance,created_at,updated_at FROM memories WHERE anchor=? AND status='active' ORDER BY importance DESC,updated_at DESC LIMIT ?
`

type ListRecentMemoriesParams struct {
	Anchor string `db:"anchor"`
	Limit  int64  `db:"limit"`
}

type ListRecentMemoriesRow struct {
	ID         string `db:"id"`
	Content    string `db:"content"`
	Anchor     string `db:"anchor"`
	SessionID  string `db:"session_id"`
	Provenance string `db:"provenance"`
	Status     string `db:"status"`
	Importance int64  `db:"importance"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

func (q *Queries) ListRecentMemories(ctx context.Context, arg ListRecentMemoriesParams) ([]ListRecentMemoriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMemories, arg.Anchor, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentMemoriesRow
	for rows.Next() {
		var i ListRecentMemoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.Anchor,
			&i.SessionID,
			&i.Provenance,
			&i.Status,
			&i.Importance,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileAttemptData = `-- name: ListReconcileAttemptData :many
SELECT data FROM records WHERE kind=? AND status=? ORDER BY key1
`

type ListReconcileAttemptDataParams struct {
	Kind   string `db:"kind"`
	Status string `db:"status"`
}

func (q *Queries) ListReconcileAttemptData(ctx context.Context, arg ListReconcileAttemptDataParams) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listReconcileAttemptData, arg.Kind, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordData = `-- name: ListRecordData :many
SELECT data FROM records WHERE kind=? ORDER BY created_at,key1,key2
`

func (q *Queries) ListRecordData(ctx context.Context, kind string) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listRecordData, kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecordDataByRun = `-- name: ListRecordDataByRun :many
SELECT data FROM records WHERE kind=? AND run_id=? ORDER BY created_at,key1,key2
`

type ListRecordDataByRunParams struct {
	Kind  string `db:"kind"`
	RunID string `db:"run_id"`
}

func (q *Queries) ListRecordDataByRun(ctx context.Context, arg ListRecordDataByRunParams) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listRecordDataByRun, arg.Kind, arg.RunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionBlocks = `-- name: ListSessionBlocks :many
SELECT sequence,data FROM session_blocks WHERE session_id=? ORDER BY sequence
`

type ListSessionBlocksRow struct {
	Sequence int64  `db:"sequence"`
	Data     []byte `db:"data"`
}

func (q *Queries) ListSessionBlocks(ctx context.Context, sessionID string) ([]ListSessionBlocksRow, error) {
	rows, err := q.db.QueryContext(ctx, listSessionBlocks, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSessionBlocksRow
	for rows.Next() {
		var i ListSessionBlocksRow
		if err := rows.Scan(&i.Sequence, &i.Data); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
SELECT s.id,s.title,s.provider_id,s.model_id,s.reasoning,s.agent_mode,s.created_at,s.updated_at FROM sessions s JOIN session_projections p ON p.session_id=s.id WHERE p.last_run_id<>'' OR EXISTS(SELECT 1 FROM session_blocks b WHERE b.session_id=s.id) OR CAST(p.blocks AS TEXT)<>'[]' ORDER BY s.updated_at DESC
`

func (q *Queries) ListSessions(ctx context.Context) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProviderID,
			&i.ModelID,
			&i.Reasoning,
			&i.AgentMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionsLimited = `-- name: ListSessionsLimited :many
SELECT s.id,s.title,s.provider_id,s.model_id,s.reasoning,s.agent_mode,s.created_at,s.updated_at FROM sessions s JOIN session_projections p ON p.session_id=s.id WHERE p.last_run_id<>'' OR EXISTS(SELECT 1 FROM session_blocks b WHERE b.session_id=s.id) OR CAST(p.blocks AS TEXT)<>'[]' ORDER BY s.updated_at DESC LIMIT ?
`

func (q *Queries) ListSessionsLimited(ctx context.Context, limit int64) ([]Session, error) {
	rows, err := q.db.QueryContext(ctx, listSessionsLimited, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Session
	for rows.Next() {
		var i Session
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.ProviderID,
			&i.ModelID,
			&i.Reasoning,
			&i.AgentMode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubagentRuns = `-- name: ListSubagentRuns :many
SELECT id, session_id, parent_run_id, parent_agent_id, tool_call_id, child_run_id, description, subagent_type, state, summary, provider, model, reasoning, capability_mode, requested_isolation, isolation, cwd, background, output, error, warning, transcript, tool_calls, turns, tokens_used, tools_used, worktree_path, completion_delivered, started_at, finished_at FROM subagent_runs ORDER BY started_at,id
`

func (q *Queries) ListSubagentRuns(ctx context.Context) ([]SubagentRun, error) {
	rows, err := q.db.QueryContext(ctx, listSubagentRuns)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubagentRun
	for rows.Next() {
		var i SubagentRun
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentRunID,
			&i.ParentAgentID,
			&i.ToolCallID,
			&i.ChildRunID,
			&i.Description,
			&i.SubagentType,
			&i.State,
			&i.Summary,
			&i.Provider,
			&i.Model,
			&i.Reasoning,
			&i.CapabilityMode,
			&i.RequestedIsolation,
			&i.Isolation,
			&i.Cwd,
			&i.Background,
			&i.Output,
			&i.Error,
			&i.Warning,
			&i.Transcript,
			&i.ToolCalls,
			&i.Turns,
			&i.TokensUsed,
			&i.ToolsUsed,
			&i.WorktreePath,
			&i.CompletionDelivered,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSubagentRunsBySession = `-- name: ListSubagentRunsBySession :many
SELECT id, session_id, parent_run_id, parent_agent_id, tool_call_id, child_run_id, description, subagent_type, state, summary, provider, model, reasoning, capability_mode, requested_isolation, isolation, cwd, background, output, error, warning, transcript, tool_calls, turns, tokens_used, tools_used, worktree_path, completion_delivered, started_at, finished_at FROM subagent_runs WHERE session_id=? ORDER BY started_at,id
`

func (q *Queries) ListSubagentRunsBySession(ctx context.Context, sessionID string) ([]SubagentRun, error) {
	rows, err := q.db.QueryContext(ctx, listSubagentRunsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SubagentRun
	for rows.Next() {
		var i SubagentRun
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.ParentRunID,
			&i.ParentAgentID,
			&i.ToolCallID,
			&i.ChildRunID,
			&i.Description,
			&i.SubagentType,
			&i.State,
			&i.Summary,
			&i.Provider,
			&i.Model,
			&i.Reasoning,
			&i.CapabilityMode,
			&i.RequestedIsolation,
			&i.Isolation,
			&i.Cwd,
			&i.Background,
			&i.Output,
			&i.Error,
			&i.Warning,
			&i.Transcript,
			&i.ToolCalls,
			&i.Turns,
			&i.TokensUsed,
			&i.ToolsUsed,
			&i.WorktreePath,
			&i.CompletionDelivered,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSucceededActionAttemptData = `-- name: ListSucceededActionAttemptData :many
SELECT data FROM records WHERE kind=? AND run_id=? AND task_id=? AND status=? ORDER BY key1
`

type ListSucceededActionAttemptDataParams struct {
	Kind   string `db:"kind"`
	RunID  string `db:"run_id"`
	TaskID string `db:"task_id"`
	Status string `db:"status"`
}

func (q *Queries) ListSucceededActionAttemptData(ctx context.Context, arg ListSucceededActionAttemptDataParams) ([][]byte, error) {
	rows, err := q.db.QueryContext(ctx, listSucceededActionAttemptData,
		arg.Kind,
		arg.RunID,
		arg.TaskID,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items [][]byte
	for rows.Next() {
		var data []byte
		if err := rows.Scan(&data); err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const maxLeaseVersion = `-- name: MaxLeaseVersion :one
SELECT CAST(COALESCE(MAX(version),0) AS INTEGER) FROM leases WHERE run_id=? AND task_id=?
`

type MaxLeaseVersionParams struct {
	RunID  string `db:"run_id"`
	TaskID string `db:"task_id"`
}

func (q *Queries) MaxLeaseVersion(ctx context.Context, arg MaxLeaseVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, maxLeaseVersion, arg.RunID, arg.TaskID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const providerRunTotalTokens = `-- name: ProviderRunTotalTokens :one
SELECT CAST(COALESCE(SUM(total_tokens),0) AS INTEGER) FROM provider_requests WHERE session_id=? AND run_id=? AND status='completed'
`

type ProviderRunTotalTokensParams struct {
	SessionID string `db:"session_id"`
	RunID     string `db:"run_id"`
}

func (q *Queries) ProviderRunTotalTokens(ctx context.Context, arg ProviderRunTotalTokensParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, providerRunTotalTokens, arg.SessionID, arg.RunID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const quarantineActionAttemptCAS = `-- name: QuarantineActionAttemptCAS :execresult
UPDATE records SET status=?,data=? WHERE kind=? AND key1=? AND status IN (?,?)
`

type QuarantineActionAttemptCASParams struct {
	Status   string `db:"status"`
	Data     []byte `db:"data"`
	Kind     string `db:"kind"`
	Key1     string `db:"key1"`
	Status_2 string `db:"status_2"`
	Status_3 string `db:"status_3"`
}

func (q *Queries) QuarantineActionAttemptCAS(ctx context.Context, arg QuarantineActionAttemptCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, quarantineActionAttemptCAS,
		arg.Status,
		arg.Data,
		arg.Kind,
		arg.Key1,
		arg.Status_2,
		arg.Status_3,
	)
}

const quarantineStartedProviderRequests = `-- name: QuarantineStartedProviderRequests :exec
UPDATE provider_requests SET status='unknown' WHERE status='started'
`

func (q *Queries) QuarantineStartedProviderRequests(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, quarantineStartedProviderRequests)
	return err
}

const resolveReconcileAttemptCAS = `-- name: ResolveReconcileAttemptCAS :execresult
UPDATE records SET status=?,data=? WHERE kind=? AND key1=? AND status=?
`

type ResolveReconcileAttemptCASParams struct {
	Status   string `db:"status"`
	Data     []byte `db:"data"`
	Kind     string `db:"kind"`
	Key1     string `db:"key1"`
	Status_2 string `db:"status_2"`
}

func (q *Queries) ResolveReconcileAttemptCAS(ctx context.Context, arg ResolveReconcileAttemptCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, resolveReconcileAttemptCAS,
		arg.Status,
		arg.Data,
		arg.Kind,
		arg.Key1,
		arg.Status_2,
	)
}

const saveCompaction = `-- name: SaveCompaction :exec
UPDATE session_projections SET model_history=?,checkpoint_generation=?,cache_epoch=?,cache_identity_hash='',updated_at=? WHERE session_id=?
`

type SaveCompactionParams struct {
	ModelHistory         []byte `db:"model_history"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	CacheEpoch           int64  `db:"cache_epoch"`
	UpdatedAt            int64  `db:"updated_at"`
	SessionID            string `db:"session_id"`
}

func (q *Queries) SaveCompaction(ctx context.Context, arg SaveCompactionParams) error {
	_, err := q.db.ExecContext(ctx, saveCompaction,
		arg.ModelHistory,
		arg.CheckpointGeneration,
		arg.CacheEpoch,
		arg.UpdatedAt,
		arg.SessionID,
	)
	return err
}

const saveRunCheckpointCAS = `-- name: SaveRunCheckpointCAS :execresult
UPDATE session_projections SET model_history=?,checkpoint_generation=?,cache_epoch=?,cache_identity_hash=?,updated_at=? WHERE session_id=? AND last_run_id=? AND checkpoint_generation=?
`

type SaveRunCheckpointCASParams struct {
	ModelHistory           []byte `db:"model_history"`
	CheckpointGeneration   int64  `db:"checkpoint_generation"`
	CacheEpoch             int64  `db:"cache_epoch"`
	CacheIdentityHash      string `db:"cache_identity_hash"`
	UpdatedAt              int64  `db:"updated_at"`
	SessionID              string `db:"session_id"`
	LastRunID              string `db:"last_run_id"`
	CheckpointGeneration_2 int64  `db:"checkpoint_generation_2"`
}

func (q *Queries) SaveRunCheckpointCAS(ctx context.Context, arg SaveRunCheckpointCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, saveRunCheckpointCAS,
		arg.ModelHistory,
		arg.CheckpointGeneration,
		arg.CacheEpoch,
		arg.CacheIdentityHash,
		arg.UpdatedAt,
		arg.SessionID,
		arg.LastRunID,
		arg.CheckpointGeneration_2,
	)
}

const saveSubagentRun = `-- name: SaveSubagentRun :execresult
UPDATE subagent_runs SET session_id=?,parent_run_id=?,parent_agent_id=?,tool_call_id=?,child_run_id=?,description=?,subagent_type=?,state=?,summary=?,provider=?,model=?,reasoning=?,capability_mode=?,requested_isolation=?,isolation=?,cwd=?,background=?,output=?,error=?,warning=?,transcript=?,tool_calls=?,turns=?,tokens_used=?,tools_used=?,worktree_path=?,completion_delivered=?,started_at=?,finished_at=? WHERE id=?
`

type SaveSubagentRunParams struct {
	SessionID           string `db:"session_id"`
	ParentRunID         string `db:"parent_run_id"`
	ParentAgentID       string `db:"parent_agent_id"`
	ToolCallID          string `db:"tool_call_id"`
	ChildRunID          string `db:"child_run_id"`
	Description         string `db:"description"`
	SubagentType        string `db:"subagent_type"`
	State               string `db:"state"`
	Summary             string `db:"summary"`
	Provider            string `db:"provider"`
	Model               string `db:"model"`
	Reasoning           string `db:"reasoning"`
	CapabilityMode      string `db:"capability_mode"`
	RequestedIsolation  string `db:"requested_isolation"`
	Isolation           string `db:"isolation"`
	Cwd                 string `db:"cwd"`
	Background          int64  `db:"background"`
	Output              string `db:"output"`
	Error               string `db:"error"`
	Warning             string `db:"warning"`
	Transcript          []byte `db:"transcript"`
	ToolCalls           int64  `db:"tool_calls"`
	Turns               int64  `db:"turns"`
	TokensUsed          int64  `db:"tokens_used"`
	ToolsUsed           []byte `db:"tools_used"`
	WorktreePath        string `db:"worktree_path"`
	CompletionDelivered int64  `db:"completion_delivered"`
	StartedAt           int64  `db:"started_at"`
	FinishedAt          int64  `db:"finished_at"`
	ID                  string `db:"id"`
}

func (q *Queries) SaveSubagentRun(ctx context.Context, arg SaveSubagentRunParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, saveSubagentRun,
		arg.SessionID,
		arg.ParentRunID,
		arg.ParentAgentID,
		arg.ToolCallID,
		arg.ChildRunID,
		arg.Description,
		arg.SubagentType,
		arg.State,
		arg.Summary,
		arg.Provider,
		arg.Model,
		arg.Reasoning,
		arg.CapabilityMode,
		arg.RequestedIsolation,
		arg.Isolation,
		arg.Cwd,
		arg.Background,
		arg.Output,
		arg.Error,
		arg.Warning,
		arg.Transcript,
		arg.ToolCalls,
		arg.Turns,
		arg.TokensUsed,
		arg.ToolsUsed,
		arg.WorktreePath,
		arg.CompletionDelivered,
		arg.StartedAt,
		arg.FinishedAt,
		arg.ID,
	)
}

const setSubagentCompletionDelivered = `-- name: SetSubagentCompletionDelivered :execresult
UPDATE subagent_runs SET completion_delivered=? WHERE id=?
`

type SetSubagentCompletionDeliveredParams struct {
	CompletionDelivered int64  `db:"completion_delivered"`
	ID                  string `db:"id"`
}

func (q *Queries) SetSubagentCompletionDelivered(ctx context.Context, arg SetSubagentCompletionDeliveredParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, setSubagentCompletionDelivered, arg.CompletionDelivered, arg.ID)
}

const touchProjection = `-- name: TouchProjection :exec
UPDATE session_projections SET updated_at=? WHERE session_id=?
`

type TouchProjectionParams struct {
	UpdatedAt int64  `db:"updated_at"`
	SessionID string `db:"session_id"`
}

func (q *Queries) TouchProjection(ctx context.Context, arg TouchProjectionParams) error {
	_, err := q.db.ExecContext(ctx, touchProjection, arg.UpdatedAt, arg.SessionID)
	return err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :execresult
UPDATE accounts SET status=?,updated_at=? WHERE provider_id=? AND id=?
`

type UpdateAccountStatusParams struct {
	Status     string `db:"status"`
	UpdatedAt  int64  `db:"updated_at"`
	ProviderID string `db:"provider_id"`
	ID         string `db:"id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAccountStatus,
		arg.Status,
		arg.UpdatedAt,
		arg.ProviderID,
		arg.ID,
	)
}

const updateAgentBlock = `-- name: UpdateAgentBlock :execresult
UPDATE session_blocks SET run_id=?,data=? WHERE session_id=? AND kind='agent' AND agent_id=?
`

type UpdateAgentBlockParams struct {
	RunID     string `db:"run_id"`
	Data      []byte `db:"data"`
	SessionID string `db:"session_id"`
	AgentID   string `db:"agent_id"`
}

func (q *Queries) UpdateAgentBlock(ctx context.Context, arg UpdateAgentBlockParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAgentBlock,
		arg.RunID,
		arg.Data,
		arg.SessionID,
		arg.AgentID,
	)
}

const updateProjectionRun = `-- name: UpdateProjectionRun :exec
UPDATE session_projections SET last_run_id=?,updated_at=? WHERE session_id=?
`

type UpdateProjectionRunParams struct {
	LastRunID string `db:"last_run_id"`
	UpdatedAt int64  `db:"updated_at"`
	SessionID string `db:"session_id"`
}

func (q *Queries) UpdateProjectionRun(ctx context.Context, arg UpdateProjectionRunParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectionRun, arg.LastRunID, arg.UpdatedAt, arg.SessionID)
	return err
}

const updateProjectionRunAfterAssistantMutation = `-- name: UpdateProjectionRunAfterAssistantMutation :exec
UPDATE session_projections SET last_run_id=?1, model_history=CASE WHEN CAST(json_extract(model_history,'$.coveredThroughSequence') AS INTEGER)>=CAST(?2 AS INTEGER) THEN '{}' ELSE model_history END, checkpoint_generation=checkpoint_generation+CASE WHEN CAST(json_extract(model_history,'$.coveredThroughSequence') AS INTEGER)>=CAST(?3 AS INTEGER) THEN 1 ELSE 0 END, updated_at=?4 WHERE session_id=?5
`

type UpdateProjectionRunAfterAssistantMutationParams struct {
	LastRunID          string `db:"last_run_id"`
	HistorySequence    int64  `db:"history_sequence"`
	GenerationSequence int64  `db:"generation_sequence"`
	UpdatedAt          int64  `db:"updated_at"`
	SessionID          string `db:"session_id"`
}

func (q *Queries) UpdateProjectionRunAfterAssistantMutation(ctx context.Context, arg UpdateProjectionRunAfterAssistantMutationParams) error {
	_, err := q.db.ExecContext(ctx, updateProjectionRunAfterAssistantMutation,
		arg.LastRunID,
		arg.HistorySequence,
		arg.GenerationSequence,
		arg.UpdatedAt,
		arg.SessionID,
	)
	return err
}

const updateSessionBlockData = `-- name: UpdateSessionBlockData :exec
UPDATE session_blocks SET data=? WHERE session_id=? AND sequence=?
`

type UpdateSessionBlockDataParams struct {
	Data      []byte `db:"data"`
	SessionID string `db:"session_id"`
	Sequence  int64  `db:"sequence"`
}

func (q *Queries) UpdateSessionBlockData(ctx context.Context, arg UpdateSessionBlockDataParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionBlockData, arg.Data, arg.SessionID, arg.Sequence)
	return err
}

const updateSessionPreferences = `-- name: UpdateSessionPreferences :execresult
UPDATE sessions SET provider_id=?,model_id=?,reasoning=?,agent_mode=?,updated_at=? WHERE id=?
`

type UpdateSessionPreferencesParams struct {
	ProviderID string `db:"provider_id"`
	ModelID    string `db:"model_id"`
	Reasoning  string `db:"reasoning"`
	AgentMode  string `db:"agent_mode"`
	UpdatedAt  int64  `db:"updated_at"`
	ID         string `db:"id"`
}

func (q *Queries) UpdateSessionPreferences(ctx context.Context, arg UpdateSessionPreferencesParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSessionPreferences,
		arg.ProviderID,
		arg.ModelID,
		arg.Reasoning,
		arg.AgentMode,
		arg.UpdatedAt,
		arg.ID,
	)
}

const updateSessionTimestamp = `-- name: UpdateSessionTimestamp :exec
UPDATE sessions SET updated_at=? WHERE id=?
`

type UpdateSessionTimestampParams struct {
	UpdatedAt int64  `db:"updated_at"`
	ID        string `db:"id"`
}

func (q *Queries) UpdateSessionTimestamp(ctx context.Context, arg UpdateSessionTimestampParams) error {
	_, err := q.db.ExecContext(ctx, updateSessionTimestamp, arg.UpdatedAt, arg.ID)
	return err
}

const updateTodoCAS = `-- name: UpdateTodoCAS :execresult
UPDATE session_todos SET goal=?,revision=?,phases=?,updated_at=? WHERE session_id=? AND revision=?
`

type UpdateTodoCASParams struct {
	Goal       string `db:"goal"`
	Revision   int64  `db:"revision"`
	Phases     []byte `db:"phases"`
	UpdatedAt  int64  `db:"updated_at"`
	SessionID  string `db:"session_id"`
	Revision_2 int64  `db:"revision_2"`
}

func (q *Queries) UpdateTodoCAS(ctx context.Context, arg UpdateTodoCASParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateTodoCAS,
		arg.Goal,
		arg.Revision,
		arg.Phases,
		arg.UpdatedAt,
		arg.SessionID,
		arg.Revision_2,
	)
}

const updateUsage = `-- name: UpdateUsage :execresult
UPDATE session_projections SET usage=? WHERE session_id=?
`

type UpdateUsageParams struct {
	Usage     []byte `db:"usage"`
	SessionID string `db:"session_id"`
}

func (q *Queries) UpdateUsage(ctx context.Context, arg UpdateUsageParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateUsage, arg.Usage, arg.SessionID)
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts(id,provider_id,email,display_name,plan,credential_ref,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?) ON CONFLICT(provider_id,id) DO UPDATE SET email=excluded.email,display_name=excluded.display_name,plan=excluded.plan,credential_ref=excluded.credential_ref,status=excluded.status,updated_at=excluded.updated_at
`

type UpsertAccountParams struct {
	ID            string `db:"id"`
	ProviderID    string `db:"provider_id"`
	Email         string `db:"email"`
	DisplayName   string `db:"display_name"`
	Plan          string `db:"plan"`
	CredentialRef string `db:"credential_ref"`
	Status        string `db:"status"`
	CreatedAt     int64  `db:"created_at"`
	UpdatedAt     int64  `db:"updated_at"`
}

func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.ID,
		arg.ProviderID,
		arg.Email,
		arg.DisplayName,
		arg.Plan,
		arg.CredentialRef,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertCredential = `-- name: UpsertCredential :exec
INSERT INTO auth_credentials(provider_id,account_id,data,created_at,updated_at) VALUES(?,?,?,?,?) ON CONFLICT(provider_id,account_id) DO UPDATE SET data=excluded.data,updated_at=excluded.updated_at
`

type UpsertCredentialParams struct {
	ProviderID string `db:"provider_id"`
	AccountID  string `db:"account_id"`
	Data       string `db:"data"`
	CreatedAt  int64  `db:"created_at"`
	UpdatedAt  int64  `db:"updated_at"`
}

func (q *Queries) UpsertCredential(ctx context.Context, arg UpsertCredentialParams) error {
	_, err := q.db.ExecContext(ctx, upsertCredential,
		arg.ProviderID,
		arg.AccountID,
		arg.Data,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertLease = `-- name: UpsertLease :exec
INSERT INTO leases(id,run_id,task_id,holder_id,status,expires_at,version,data) VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET run_id=excluded.run_id,task_id=excluded.task_id,holder_id=excluded.holder_id,status=excluded.status,expires_at=excluded.expires_at,version=excluded.version,data=excluded.data
`

type UpsertLeaseParams struct {
	ID        string `db:"id"`
	RunID     string `db:"run_id"`
	TaskID    string `db:"task_id"`
	HolderID  string `db:"holder_id"`
	Status    string `db:"status"`
	ExpiresAt int64  `db:"expires_at"`
	Version   int64  `db:"version"`
	Data      []byte `db:"data"`
}

func (q *Queries) UpsertLease(ctx context.Context, arg UpsertLeaseParams) error {
	_, err := q.db.ExecContext(ctx, upsertLease,
		arg.ID,
		arg.RunID,
		arg.TaskID,
		arg.HolderID,
		arg.Status,
		arg.ExpiresAt,
		arg.Version,
		arg.Data,
	)
	return err
}

const upsertProviderRequest = `-- name: UpsertProviderRequest :exec
INSERT INTO provider_requests(request_id,provider_request_id,session_id,run_id,request_kind,provider,model,transport,cache_epoch,checkpoint_generation,input_tokens,cached_tokens,cache_write_tokens,output_tokens,reasoning_tokens,total_tokens,cache_reported,status,started_at,completed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(request_id) DO UPDATE SET provider_request_id=excluded.provider_request_id,session_id=excluded.session_id,run_id=excluded.run_id,request_kind=excluded.request_kind,provider=excluded.provider,model=excluded.model,transport=excluded.transport,cache_epoch=excluded.cache_epoch,checkpoint_generation=excluded.checkpoint_generation,input_tokens=excluded.input_tokens,cached_tokens=excluded.cached_tokens,cache_write_tokens=excluded.cache_write_tokens,output_tokens=excluded.output_tokens,reasoning_tokens=excluded.reasoning_tokens,total_tokens=excluded.total_tokens,cache_reported=excluded.cache_reported,status=excluded.status,started_at=MIN(provider_requests.started_at,excluded.started_at),completed_at=excluded.completed_at
`

type UpsertProviderRequestParams struct {
	RequestID            string `db:"request_id"`
	ProviderRequestID    string `db:"provider_request_id"`
	SessionID            string `db:"session_id"`
	RunID                string `db:"run_id"`
	RequestKind          string `db:"request_kind"`
	Provider             string `db:"provider"`
	Model                string `db:"model"`
	Transport            string `db:"transport"`
	CacheEpoch           int64  `db:"cache_epoch"`
	CheckpointGeneration int64  `db:"checkpoint_generation"`
	InputTokens          int64  `db:"input_tokens"`
	CachedTokens         int64  `db:"cached_tokens"`
	CacheWriteTokens     int64  `db:"cache_write_tokens"`
	OutputTokens         int64  `db:"output_tokens"`
	ReasoningTokens      int64  `db:"reasoning_tokens"`
	TotalTokens          int64  `db:"total_tokens"`
	CacheReported        int64  `db:"cache_reported"`
	Status               string `db:"status"`
	StartedAt            int64  `db:"started_at"`
	CompletedAt          int64  `db:"completed_at"`
}

func (q *Queries) UpsertProviderRequest(ctx context.Context, arg UpsertProviderRequestParams) error {
	_, err := q.db.ExecContext(ctx, upsertProviderRequest,
		arg.RequestID,
		arg.ProviderRequestID,
		arg.SessionID,
		arg.RunID,
		arg.RequestKind,
		arg.Provider,
		arg.Model,
		arg.Transport,
		arg.CacheEpoch,
		arg.CheckpointGeneration,
		arg.InputTokens,
		arg.CachedTokens,
		arg.CacheWriteTokens,
		arg.OutputTokens,
		arg.ReasoningTokens,
		arg.TotalTokens,
		arg.CacheReported,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
	)
	return err
}

const upsertRecap = `-- name: UpsertRecap :one
INSERT INTO recaps(session_id,anchor,covered_boundary,revision,goal,summary,open_items,updated_at) VALUES(?,?,?,1,?,?,?,?) ON CONFLICT(session_id) DO UPDATE SET covered_boundary=excluded.covered_boundary,revision=recaps.revision+1,goal=excluded.goal,summary=excluded.summary,open_items=excluded.open_items,updated_at=excluded.updated_at WHERE recaps.anchor=excluded.anchor RETURNING revision
`

type UpsertRecapParams struct {
	SessionID       string `db:"session_id"`
	Anchor          string `db:"anchor"`
	CoveredBoundary string `db:"covered_boundary"`
	Goal            string `db:"goal"`
	Summary         string `db:"summary"`
	OpenItems       string `db:"open_items"`
	UpdatedAt       int64  `db:"updated_at"`
}

func (q *Queries) UpsertRecap(ctx context.Context, arg UpsertRecapParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertRecap,
		arg.SessionID,
		arg.Anchor,
		arg.CoveredBoundary,
		arg.Goal,
		arg.Summary,
		arg.OpenItems,
		arg.UpdatedAt,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const upsertRecord = `-- name: UpsertRecord :exec
INSERT INTO records(kind,key1,key2,run_id,task_id,status,created_at,tool_name,idempotency_key,data) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(kind,key1,key2) DO UPDATE SET run_id=excluded.run_id,task_id=excluded.task_id,status=excluded.status,created_at=excluded.created_at,tool_name=excluded.tool_name,idempotency_key=excluded.idempotency_key,data=excluded.data
`

type UpsertRecordParams struct {
	Kind           string `db:"kind"`
	Key1           string `db:"key1"`
	Key2           string `db:"key2"`
	RunID          string `db:"run_id"`
	TaskID         string `db:"task_id"`
	Status         string `db:"status"`
	CreatedAt      int64  `db:"created_at"`
	ToolName       string `db:"tool_name"`
	IdempotencyKey string `db:"idempotency_key"`
	Data           []byte `db:"data"`
}

func (q *Queries) UpsertRecord(ctx context.Context, arg UpsertRecordParams) error {
	_, err := q.db.ExecContext(ctx, upsertRecord,
		arg.Kind,
		arg.Key1,
		arg.Key2,
		arg.RunID,
		arg.TaskID,
		arg.Status,
		arg.CreatedAt,
		arg.ToolName,
		arg.IdempotencyKey,
		arg.Data,
	)
	return err
}
