// Code generated by cmd/gen-contracts; DO NOT EDIT.
// The Go source of truth is internal/desktopipc/protocol.go and
// internal/app/contracts.go. Regenerate with: make contracts.

use serde::{Deserialize, Serialize};
use serde_json::Value;

pub const PROTOCOL_VERSION: u32 = 1;
pub const MAX_CONTROL_FRAME_BYTES: usize = 16777216;
pub const MAX_BINARY_CHUNK_BYTES: usize = 262144;
pub const MAX_REASSEMBLED_BINARY: usize = 268435456;

#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, Hash, PartialEq)]
pub enum Method {
    #[serde(rename = "initialise")]
    Initialise,
    #[serde(rename = "reconnect_snapshot")]
    ReconnectSnapshot,
    #[serde(rename = "start_turn")]
    StartTurn,
    #[serde(rename = "guide")]
    Guide,
    #[serde(rename = "follow_up")]
    FollowUp,
    #[serde(rename = "cancel_active")]
    CancelActive,
    #[serde(rename = "execute")]
    Execute,
    #[serde(rename = "import_attachment")]
    ImportAttachment,
    #[serde(rename = "import_clipboard_image")]
    ImportClipboardImage,
    #[serde(rename = "attachment_data_url")]
    AttachmentDataUrl,
    #[serde(rename = "search_sessions")]
    SearchSessions,
    #[serde(rename = "resume_session")]
    ResumeSession,
    #[serde(rename = "session_tree")]
    SessionTree,
    #[serde(rename = "navigate_session_tree")]
    NavigateSessionTree,
    #[serde(rename = "create_session_fork")]
    CreateSessionFork,
    #[serde(rename = "set_session_entry_label")]
    SetSessionEntryLabel,
    #[serde(rename = "export_session")]
    ExportSession,
    #[serde(rename = "share_session")]
    ShareSession,
    #[serde(rename = "fork_session")]
    ForkSession,
    #[serde(rename = "pull_request_dashboard")]
    PullRequestDashboard,
    #[serde(rename = "pull_request_detail")]
    PullRequestDetail,
    #[serde(rename = "mutate_pull_request")]
    MutatePullRequest,
    #[serde(rename = "set_pull_request_monitor")]
    SetPullRequestMonitor,
    #[serde(rename = "skill_catalog")]
    SkillCatalog,
    #[serde(rename = "hook_catalog")]
    HookCatalog,
    #[serde(rename = "marketplace_catalog")]
    MarketplaceCatalog,
    #[serde(rename = "usage_report")]
    UsageReport,
    #[serde(rename = "workspace_changes")]
    WorkspaceChanges,
    #[serde(rename = "workspace_change")]
    WorkspaceChange,
    #[serde(rename = "workspace_entries")]
    WorkspaceEntries,
    #[serde(rename = "search_workspace_files")]
    SearchWorkspaceFiles,
    #[serde(rename = "workspace_file")]
    WorkspaceFile,
    #[serde(rename = "create_project")]
    CreateProject,
    #[serde(rename = "open_project")]
    OpenProject,
    #[serde(rename = "open_project_session")]
    OpenProjectSession,
    #[serde(rename = "system_fonts")]
    SystemFonts,
    #[serde(rename = "list_terminals")]
    ListTerminals,
    #[serde(rename = "create_terminal")]
    CreateTerminal,
    #[serde(rename = "write_terminal")]
    WriteTerminal,
    #[serde(rename = "resize_terminal")]
    ResizeTerminal,
    #[serde(rename = "close_terminal")]
    CloseTerminal,
    #[serde(rename = "open_terminal")]
    OpenTerminal,
    #[serde(rename = "terminal_replay")]
    TerminalReplay,
    #[serde(rename = "begin_attachment_transfer")]
    BeginAttachmentTransfer,
    #[serde(rename = "commit_attachment")]
    CommitAttachment,
    #[serde(rename = "abort_attachment")]
    AbortAttachment,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, Hash, PartialEq)]
pub enum ActionKind {
    #[serde(rename = "login")]
    Login,
    #[serde(rename = "logout")]
    Logout,
    #[serde(rename = "new_session")]
    NewSession,
    #[serde(rename = "list_sessions")]
    ListSessions,
    #[serde(rename = "list_usage")]
    ListUsage,
    #[serde(rename = "resume_session")]
    ResumeSession,
    #[serde(rename = "refresh_session")]
    RefreshSession,
    #[serde(rename = "rename_session")]
    RenameSession,
    #[serde(rename = "pin_session")]
    PinSession,
    #[serde(rename = "archive_session")]
    ArchiveSession,
    #[serde(rename = "archive_inactive_sessions")]
    ArchiveInactiveSessions,
    #[serde(rename = "remove_project")]
    RemoveProject,
    #[serde(rename = "mark_session_unread")]
    MarkSessionUnread,
    #[serde(rename = "compact")]
    Compact,
    #[serde(rename = "resolve_approval")]
    ResolveApproval,
    #[serde(rename = "resolve_user_input")]
    ResolveUserInput,
    #[serde(rename = "resolve_plan")]
    ResolvePlan,
    #[serde(rename = "set_approval_mode")]
    SetApprovalMode,
    #[serde(rename = "set_language")]
    SetLanguage,
    #[serde(rename = "set_queue_mode")]
    SetQueueMode,
    #[serde(rename = "reconcile_attempt")]
    ReconcileAttempt,
    #[serde(rename = "inspect_agent")]
    InspectAgent,
    #[serde(rename = "list_agent_types")]
    ListAgentTypes,
    #[serde(rename = "list_personas")]
    ListPersonas,
    #[serde(rename = "cancel_agent")]
    CancelAgent,
    #[serde(rename = "refresh_mcp")]
    RefreshMcp,
    #[serde(rename = "reconnect_mcp")]
    ReconnectMcp,
    #[serde(rename = "set_mcp_enabled")]
    SetMcpEnabled,
    #[serde(rename = "upsert_mcp_server")]
    UpsertMcpServer,
    #[serde(rename = "delete_mcp_server")]
    DeleteMcpServer,
    #[serde(rename = "get_mcp_prompt")]
    GetMcpPrompt,
    #[serde(rename = "subscribe_mcp_resource")]
    SubscribeMcpResource,
    #[serde(rename = "unsubscribe_mcp_resource")]
    UnsubscribeMcpResource,
    #[serde(rename = "authenticate_mcp_server")]
    AuthenticateMcpServer,
    #[serde(rename = "unauthenticate_mcp_server")]
    UnauthenticateMcpServer,
    #[serde(rename = "marketplace_add")]
    MarketplaceAdd,
    #[serde(rename = "marketplace_remove")]
    MarketplaceRemove,
    #[serde(rename = "marketplace_update")]
    MarketplaceUpdate,
    #[serde(rename = "marketplace_list")]
    MarketplaceList,
    #[serde(rename = "marketplace_discover")]
    MarketplaceDiscover,
    #[serde(rename = "marketplace_install")]
    MarketplaceInstall,
    #[serde(rename = "marketplace_uninstall")]
    MarketplaceUninstall,
    #[serde(rename = "marketplace_installed")]
    MarketplaceInstalled,
    #[serde(rename = "marketplace_upgrade")]
    MarketplaceUpgrade,
    #[serde(rename = "marketplace_enable")]
    MarketplaceEnable,
    #[serde(rename = "marketplace_disable")]
    MarketplaceDisable,
    #[serde(rename = "list_custom_commands")]
    ListCustomCommands,
    #[serde(rename = "list_themes")]
    ListThemes,
    #[serde(rename = "list_skills")]
    ListSkills,
    #[serde(rename = "list_plugins")]
    ListPlugins,
    #[serde(rename = "set_plugin_imported")]
    SetPluginImported,
    #[serde(rename = "list_hooks")]
    ListHooks,
    #[serde(rename = "set_plugin_hooks_trusted")]
    SetPluginHooksTrusted,
    #[serde(rename = "set_hook_enabled")]
    SetHookEnabled,
    #[serde(rename = "reload_skills")]
    ReloadSkills,
    #[serde(rename = "set_skill_enabled")]
    SetSkillEnabled,
    #[serde(rename = "list_memories")]
    ListMemories,
    #[serde(rename = "remember")]
    Remember,
    #[serde(rename = "forget_memory")]
    ForgetMemory,
    #[serde(rename = "show_recap")]
    ShowRecap,
    #[serde(rename = "list_models")]
    ListModels,
    #[serde(rename = "list_model_providers")]
    ListModelProviders,
    #[serde(rename = "discover_provider_models")]
    DiscoverProviderModels,
    #[serde(rename = "set_model_provider")]
    SetModelProvider,
    #[serde(rename = "set_model_enabled")]
    SetModelEnabled,
    #[serde(rename = "list_model_routes")]
    ListModelRoutes,
    #[serde(rename = "set_model_route")]
    SetModelRoute,
    #[serde(rename = "reset_model_route")]
    ResetModelRoute,
    #[serde(rename = "set_subagent_concurrency")]
    SetSubagentConcurrency,
    #[serde(rename = "set_subagent_depth")]
    SetSubagentDepth,
    #[serde(rename = "set_shell_concurrency")]
    SetShellConcurrency,
    #[serde(rename = "set_shell_max_wall_clock")]
    SetShellMaxWallClock,
    #[serde(rename = "set_subagent_await_timeout")]
    SetSubagentAwaitTimeout,
    #[serde(rename = "set_subagent_idle_timeout")]
    SetSubagentIdleTimeout,
    #[serde(rename = "set_chatgpt_fast_mode")]
    SetChatgptFastMode,
    #[serde(rename = "set_session_preferences")]
    SetSessionPreferences,
    #[serde(rename = "list_background")]
    ListBackground,
    #[serde(rename = "start_background")]
    StartBackground,
    #[serde(rename = "stop_background")]
    StopBackground,
    #[serde(rename = "logs_background")]
    LogsBackground,
    #[serde(rename = "list_git_branches")]
    ListGitBranches,
    #[serde(rename = "switch_git_branch")]
    SwitchGitBranch,
    #[serde(rename = "create_git_branch")]
    CreateGitBranch,
    #[serde(rename = "get_security_config")]
    GetSecurityConfig,
    #[serde(rename = "set_security_config")]
    SetSecurityConfig,
    #[serde(rename = "start_security_scan")]
    StartSecurityScan,
    #[serde(rename = "cancel_security_scan")]
    CancelSecurityScan,
    #[serde(rename = "resume_security_scan")]
    ResumeSecurityScan,
    #[serde(rename = "list_security_scans")]
    ListSecurityScans,
    #[serde(rename = "get_security_scan")]
    GetSecurityScan,
    #[serde(rename = "list_security_findings")]
    ListSecurityFindings,
    #[serde(rename = "get_security_finding")]
    GetSecurityFinding,
    #[serde(rename = "set_security_finding_triage")]
    SetSecurityFindingTriage,
    #[serde(rename = "patch_security_findings")]
    PatchSecurityFindings,
    #[serde(rename = "patch_security_findings_with_pr")]
    PatchSecurityFindingsWithPr,
    #[serde(rename = "export_security_scan")]
    ExportSecurityScan,
    #[serde(rename = "publish_security_scan")]
    PublishSecurityScan,
    #[serde(rename = "reconcile_security_publication")]
    ReconcileSecurityPublication,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, Eq, Hash, PartialEq)]
pub enum EventKind {
    #[serde(rename = "bootstrap_done")]
    BootstrapDone,
    #[serde(rename = "session_loaded")]
    SessionLoaded,
    #[serde(rename = "todo_updated")]
    TodoUpdated,
    #[serde(rename = "run_started")]
    RunStarted,
    #[serde(rename = "context_usage")]
    ContextUsage,
    #[serde(rename = "context_profile")]
    ContextProfile,
    #[serde(rename = "agent_state")]
    AgentState,
    #[serde(rename = "agent_detail")]
    AgentDetail,
    #[serde(rename = "provider_retry")]
    ProviderRetry,
    #[serde(rename = "thinking_delta")]
    ThinkingDelta,
    #[serde(rename = "text_delta")]
    TextDelta,
    #[serde(rename = "projection_resync")]
    ProjectionResync,
    #[serde(rename = "tool_started")]
    ToolStarted,
    #[serde(rename = "tool_update")]
    ToolUpdate,
    #[serde(rename = "tool_finished")]
    ToolFinished,
    #[serde(rename = "diff_ready")]
    DiffReady,
    #[serde(rename = "approval_requested")]
    ApprovalRequested,
    #[serde(rename = "approval_resolved")]
    ApprovalResolved,
    #[serde(rename = "user_input_requested")]
    UserInputRequested,
    #[serde(rename = "user_input_resolved")]
    UserInputResolved,
    #[serde(rename = "plan_proposed")]
    PlanProposed,
    #[serde(rename = "plan_resolved")]
    PlanResolved,
    #[serde(rename = "approval_mode")]
    ApprovalMode,
    #[serde(rename = "model_catalog")]
    ModelCatalog,
    #[serde(rename = "model_providers")]
    ModelProviders,
    #[serde(rename = "skill_catalog")]
    SkillCatalog,
    #[serde(rename = "plugin_catalog")]
    PluginCatalog,
    #[serde(rename = "hook_catalog")]
    HookCatalog,
    #[serde(rename = "auth_state")]
    AuthState,
    #[serde(rename = "marketplace_catalog")]
    MarketplaceCatalog,
    #[serde(rename = "command_catalog")]
    CommandCatalog,
    #[serde(rename = "theme_catalog")]
    ThemeCatalog,
    #[serde(rename = "security_config_state")]
    SecurityConfigState,
    #[serde(rename = "mcp_state")]
    McpState,
    #[serde(rename = "recovery_state")]
    RecoveryState,
    #[serde(rename = "run_finished")]
    RunFinished,
    #[serde(rename = "run_failed")]
    RunFailed,
    #[serde(rename = "run_cancelled")]
    RunCancelled,
    #[serde(rename = "hook_started")]
    HookStarted,
    #[serde(rename = "hook_finished")]
    HookFinished,
    #[serde(rename = "hook_diagnostic")]
    HookDiagnostic,
    #[serde(rename = "memory_state")]
    MemoryState,
    #[serde(rename = "recap_state")]
    RecapState,
    #[serde(rename = "model_routes")]
    ModelRoutes,
    #[serde(rename = "background_state")]
    BackgroundState,
    #[serde(rename = "background_logs")]
    BackgroundLogs,
    #[serde(rename = "git_branches")]
    GitBranches,
    #[serde(rename = "usage_report")]
    UsageReport,
    #[serde(rename = "security_scan_state")]
    SecurityScanState,
    #[serde(rename = "security_scan_list")]
    SecurityScanList,
    #[serde(rename = "security_finding_list")]
    SecurityFindingList,
    #[serde(rename = "security_finding_detail")]
    SecurityFindingDetail,
    #[serde(rename = "security_patch_state")]
    SecurityPatchState,
    #[serde(rename = "security_publication_state")]
    SecurityPublicationState,
    #[serde(rename = "bridge_error")]
    BridgeError,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct ProtocolError {
    pub code: String,
    pub message: String,
    #[serde(default)]
    pub retryable: bool,
}

#[derive(Clone, Debug, Default, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct BinaryMetadata {
    pub transfer_id: String,
    #[serde(default)]
    pub purpose: String,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub sequence: u64,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub media_type: String,
    pub byte_length: i64,
    pub sha256: String,
    #[serde(default)]
    pub index: usize,
    #[serde(default)]
    pub count: usize,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct Envelope {
    pub version: u32,
    pub kind: String,
    #[serde(default)]
    pub id: String,
    #[serde(default)]
    pub client_id: String,
    #[serde(default)]
    pub workspace_id: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub method: Option<Method>,
    #[serde(default)]
    pub channel: String,
    #[serde(default)]
    pub sequence: u64,
    #[serde(default)]
    pub payload: Value,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<ProtocolError>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub binary: Option<BinaryMetadata>,
}

impl Envelope {
    pub fn request(id: impl Into<String>, method: Method, payload: Value) -> Self {
        Self {
            version: PROTOCOL_VERSION,
            kind: "request".into(),
            id: id.into(),
            client_id: String::new(),
            workspace_id: String::new(),
            method: Some(method),
            channel: String::new(),
            sequence: 0,
            payload,
            error: None,
            binary: None,
        }
    }
}
