// Code generated by cmd/gen-contracts; DO NOT EDIT.
// The Go source of truth is internal/app/contracts.go (plus the desktop
// bridge-local event kinds). Regenerate with: make contracts

/** Every action kind accepted by the runtime (internal/app AllActionKinds). */
export type ActionKind =
  | "login"
  | "logout"
  | "new_session"
  | "list_sessions"
  | "list_usage"
  | "resume_session"
  | "refresh_session"
  | "rename_session"
  | "pin_session"
  | "archive_session"
  | "archive_inactive_sessions"
  | "mark_session_unread"
  | "compact"
  | "resolve_approval"
  | "resolve_user_input"
  | "resolve_plan"
  | "set_approval_mode"
  | "set_language"
  | "set_queue_mode"
  | "reconcile_attempt"
  | "inspect_agent"
  | "list_agent_types"
  | "list_personas"
  | "cancel_agent"
  | "refresh_mcp"
  | "reconnect_mcp"
  | "set_mcp_enabled"
  | "upsert_mcp_server"
  | "delete_mcp_server"
  | "list_skills"
  | "list_plugins"
  | "set_plugin_imported"
  | "list_hooks"
  | "set_plugin_hooks_trusted"
  | "set_hook_enabled"
  | "reload_skills"
  | "set_skill_enabled"
  | "list_memories"
  | "remember"
  | "forget_memory"
  | "show_recap"
  | "list_models"
  | "list_model_providers"
  | "discover_provider_models"
  | "set_model_provider"
  | "set_model_enabled"
  | "list_model_routes"
  | "set_model_route"
  | "reset_model_route"
  | "set_subagent_concurrency"
  | "set_subagent_depth"
  | "set_shell_concurrency"
  | "set_subagent_await_timeout"
  | "set_chatgpt_fast_mode"
  | "set_session_preferences"
  | "list_background"
  | "start_background"
  | "stop_background"
  | "logs_background"
  | "list_git_branches"
  | "switch_git_branch"
  | "create_git_branch"
;

/** Every runtime event kind (internal/app AllEventKinds) plus desktop bridge-local kinds. */
export type EventKind =
  | "bootstrap_done"
  | "session_loaded"
  | "todo_updated"
  | "run_started"
  | "context_usage"
  | "context_profile"
  | "agent_state"
  | "agent_detail"
  | "provider_retry"
  | "thinking_delta"
  | "text_delta"
  | "projection_resync"
  | "tool_started"
  | "tool_update"
  | "tool_finished"
  | "diff_ready"
  | "approval_requested"
  | "approval_resolved"
  | "user_input_requested"
  | "user_input_resolved"
  | "plan_proposed"
  | "plan_resolved"
  | "approval_mode"
  | "model_catalog"
  | "model_providers"
  | "skill_catalog"
  | "plugin_catalog"
  | "hook_catalog"
  | "auth_state"
  | "mcp_state"
  | "recovery_state"
  | "run_finished"
  | "run_failed"
  | "run_cancelled"
  | "hook_started"
  | "hook_finished"
  | "hook_diagnostic"
  | "memory_state"
  | "recap_state"
  | "model_routes"
  | "background_state"
  | "background_logs"
  | "git_branches"
  | "usage_report"
  | "bridge_error"
;

export const ACTION_KINDS: readonly ActionKind[] = [
  "login",
  "logout",
  "new_session",
  "list_sessions",
  "list_usage",
  "resume_session",
  "refresh_session",
  "rename_session",
  "pin_session",
  "archive_session",
  "archive_inactive_sessions",
  "mark_session_unread",
  "compact",
  "resolve_approval",
  "resolve_user_input",
  "resolve_plan",
  "set_approval_mode",
  "set_language",
  "set_queue_mode",
  "reconcile_attempt",
  "inspect_agent",
  "list_agent_types",
  "list_personas",
  "cancel_agent",
  "refresh_mcp",
  "reconnect_mcp",
  "set_mcp_enabled",
  "upsert_mcp_server",
  "delete_mcp_server",
  "list_skills",
  "list_plugins",
  "set_plugin_imported",
  "list_hooks",
  "set_plugin_hooks_trusted",
  "set_hook_enabled",
  "reload_skills",
  "set_skill_enabled",
  "list_memories",
  "remember",
  "forget_memory",
  "show_recap",
  "list_models",
  "list_model_providers",
  "discover_provider_models",
  "set_model_provider",
  "set_model_enabled",
  "list_model_routes",
  "set_model_route",
  "reset_model_route",
  "set_subagent_concurrency",
  "set_subagent_depth",
  "set_shell_concurrency",
  "set_subagent_await_timeout",
  "set_chatgpt_fast_mode",
  "set_session_preferences",
  "list_background",
  "start_background",
  "stop_background",
  "logs_background",
  "list_git_branches",
  "switch_git_branch",
  "create_git_branch",
];

export const EVENT_KINDS: readonly EventKind[] = [
  "bootstrap_done",
  "session_loaded",
  "todo_updated",
  "run_started",
  "context_usage",
  "context_profile",
  "agent_state",
  "agent_detail",
  "provider_retry",
  "thinking_delta",
  "text_delta",
  "projection_resync",
  "tool_started",
  "tool_update",
  "tool_finished",
  "diff_ready",
  "approval_requested",
  "approval_resolved",
  "user_input_requested",
  "user_input_resolved",
  "plan_proposed",
  "plan_resolved",
  "approval_mode",
  "model_catalog",
  "model_providers",
  "skill_catalog",
  "plugin_catalog",
  "hook_catalog",
  "auth_state",
  "mcp_state",
  "recovery_state",
  "run_finished",
  "run_failed",
  "run_cancelled",
  "hook_started",
  "hook_finished",
  "hook_diagnostic",
  "memory_state",
  "recap_state",
  "model_routes",
  "background_state",
  "background_logs",
  "git_branches",
  "usage_report",
  "bridge_error",
];
